/*
  Authors : initappz (Rahul Jograna)
  Website : https://initappz.com/
  App Name : Foodies Full App Flutter
  This App Template Source code is licensed as per the
  terms found in the Website https://initappz.com/license
  Copyright and Good Faith Purchasers © 2022-present initappz.
*/
import 'package:get/get.dart';

class LocaleString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          "Profile": "Profile",
          "Your Category": "Your Category",
          "Your Food": "Your Food",
          "Edit Profile": "Edit Profile",
          "Orders": "Orders",
          "Bookings": "Bookings",
          "Reviews": "Reviews",
          "Change password": "Change password",
          "Contact Us": "Contact Us",
          "Languages": "Languages",
          "Chats": "Chats",
          "About Us": "About Us",
          "FAQs": "FAQs",
          "Terms & Conditions": "Terms & Conditions",
          "Privacy Policy": "Privacy Policy",
          "Help": "Help",
          "Log Out": "Log Out",
          "Add Admin Category": "Add Admin Category",
          "Cancel": "Cancel",
          "Submit": "Submit",
          "Categories": "Categories",
          "Admin": "Admin",
          "Store": "Store",
          "Are you sure": "Are you sure",
          "After confirming it, this category will disappear from your outlet. later you can activate it again.":
              "After confirming it, this category will disappear from your outlet. later you can activate it again.",
          "Confirm": "Confirm",
          "to delete Italian ?": "to delete Italian ?",
          "Delete": "Delete",
          "Add New!": "Add New!",
          "Category Name": "Category Name",
          "OK": "OK",
          "Edit": "Edit",
          "new": "new",
          "Add Food": "Add Food",
          "Update Food": "Update Food",
          "Category": "Category",
          "Food Name": "Food Name",
          "Real Price": "Real Price",
          "Discount Price": "Discount Price",
          "Veg": "Veg",
          "Short  description": "Short  description",
          "Status": "Status",
          "Choose From'": "Choose From",
          "Camera": "Camera",
          "Gallery": "Gallery",
          "Size?": "Size?",
          "(Regualar,Medium,Large)": "(Regualar,Medium,Large)",
          "Add-ons": "Add-ons",
          "(Extras,cold drinks)": "(Extras,cold drinks)",
          "Update": "Update",
          "Add Store Category": "Add Store Category",
          "Update  Store Category": "Update  Store Category",
          "Add Category Name": "Add Category Name",
          "Select Category": "Select Category",
          "Get Orders With Dates": "Get Orders With Dates",
          "Open Time": "Open Time",
          "Close Time": "Close Time",
          "Get Results": "Get Results",
          "Total": "Total",
          "Commission": "Commission",
          "Amount Received": "Amount Received",
          "Id": "Id",
          "Order on": "Order on",
          "Items": "Items",
          "Total Guest": "Total Guest",
          "Book Date": "Book Date",
          "Guest Name": "Guest Name",
          "Guest Email": "Guest Email",
          "Accept": "Accept",
          "Reject": "Reject",
          "Complete": "Complete",
          "Rejected": "Rejected",
          "Completed": "Completed",
          "Full Name": "Full Name",
          "Email Address": "Email Address",
          "Message": "Message",
          "Update Cuisine": "Update Cuisine",
          "Select Driver": "Select Driver",
          "Restaurant Name": "Restaurant Name",
          "Restaurant Address": "Restaurant Address",
          "Restaurant Landmark": "Restaurant Landmark",
          "Pincode": "Pincode",
          "Latitude": "Latitude",
          "Longitute": "Longitute",
          "Cost For Two": "Cost For Two",
          "Phone": "Phone",
          "Estimate Delivery Time": "Estimate Delivery Time",
          "Restaurant Description": "Restaurant Description",
          "Select Cuisine": "Select Cuisine",
          "Is Open": "Is Open",
          "Upload Your Restaurant Cover Image":
              "Upload Your Restaurant Cover Image",
          "Upload Gallery Image": "Upload Gallery Image",
          "SUBMIT": "SUBMIT",
          "Image": "Image",
          "Connection Failed": "Connection Failed",
          "Could not connect to network,": "Could not connect to network,",
          "Please check and try again.": "Please check and try again.",
          "retry": "retry",
          "Foods": "Foods",
          "Search foods": "Search foods",
          "Non Veg": "Non Veg",
          "Bruschetta": "Bruschetta",
          "Bruschetta is an antipasto from Italy consisting":
              "Bruschetta is an antipasto from Italy consisting",
          "Reset Password": "Reset Password",
          "Enter your email address or phone number and we will send a verification code to generate a new password":
              "Enter your email address or phone number and we will send a verification code to generate a new password:",
          "Send OTP": "Send OTP",
          "Generate New Password": "Generate New Password",
          "New Password": "New Password",
          "Confirm Password": "Confirm Password",
          "Update Password": "Update Password",
          "Business Insights": "Business Insights",
          "Deliverd Orders": "Deliverd Orders",
          "See More": "See More",
          "Today": "Today",
          "This Week :": "This Week :",
          "This Month :": "This Month :",
          "Get more orders from": "Get more orders from",
          "Items with grocery images lead to more orders compared to items without them.Add photos to your menu items to get more orders.":
              "Items with grocery images lead to more orders compared to items without them.Add photos to your menu items to get more orders.:",
          "Rejected Orders": "Rejected Orders",
          "Lost sale from orders rejected by you":
              "Lost sale from orders rejected by you",
          "Improve yourself": "Improve yourself",
          "Great Work!": "Great Work!",
          "You have some rejected and cancelled orders on your current month's stats, this will impact on your future sells, improve your self":
              "You have some rejected and cancelled orders on your current month's stats, this will impact on your future sells, improve your self:",
          "You have accepted all orders till now in this month":
              "You have accepted all orders till now in this month",
          "Customer Complaints": "Customer Complaints",
          "Details from": "Details from",
          "Top Items in your menu": "Top Items in your menu",
          "Menu items": "Menu items",
          "Quantity Sold": "Quantity Sold",
          "Log In": "Log In",
          "Password": "Password",
          "Forgot Password?": "Forgot Password?",
          "SIGN IN": "SIGN IN",
          "Message...": "Message...",
          "Order Details": "Order Details",
          "Item Total": "Item Total",
          "Taxes & charges": "Taxes & charges",
          "Delivery Cost": "Delivery Cost",
          "Discount": "Discount",
          "Wallet Discount": "Wallet Discount",
          "Grand Total": "Grand Total",
          "Order ID": "Order ID",
          "Payment Method": "Payment Method",
          "Delivery On": "Delivery On",
          "Delivery To": "Delivery To",
          "User Information": "User Information",
          "Driver Information": "Driver Information",
          "Update Status": "Update Status",
          "Choose Status": "Choose Status",
          "Ongoing": "Ongoing",
          "New Order": "New Order",
          "Ongoing Order": "Ongoing Order",
          "Past Order": "Past Order",
          "No New Orders Found": "No New Orders Found",
          "ORDER ID :": "ORDER ID :",
          "ORDERED ON": "ORDERED ON",
          "TOTAL AMOUNT": "TOTAL AMOUNT",
          "No Ongoing Orders Found": "No Ongoing Orders Found",
          "No Old Orders Found": "No Old Orders Found",
          "Your Reviews": "Your Reviews",
          "Products Reviews": "Products Reviews",
          "No Reviews Found": "No Reviews Found",
          "No Internet Connection": "No Internet Connection",
          "Please wait": "Please wait",
          "Chart View": "Chart View",
          "Orders Trends'": "Orders Trends'",
          "Month's distribution of your orders":
              "Month's distribution of your orders",
          "Total number of orders today": "Total number of orders today",
          "Total number of orders weekly": "Total number of orders weekly",
          "Total number of orders monthly": "Total number of orders monthly",
          "Analytics": "Analytics",
          "Account": "Account",
          "Available": "Available",
          "Hide": "Hide",
          "No": "No",
          "Yes": "Yes",
          "Already added": "Already added",
          "Add item to": "Add item to",
          "Add-ons name": "Add-ons name",
          "Add-ons price": "Add-ons price",
          "Ok": "Ok",
          "Update item to": "Update item to",
          "Add Add-ons!": "Add Add-ons!",
          "Title": "Title",
          "Addon already exist with this name":
              "Addon already exist with this name",
          "Update Add-ons! Title": "Update Add-ons! Title",
          "Select Type": "Select Type",
          "Only One": "Only One",
          "Multiple": "Multiple",
          "All Fields Are Required": "All Fields Are Required",
          "Successfully Add": "Successfully Add",
          "Successfully Updated": "Successfully Updated",
          "Please select category": "Please select category",
          "Requested": "Requested",
          "Comlete": "Comlete",
          "Updating Status": "Updating Status",
          "Email is not valid": "Email is not valid",
          "New Mail Request Received": "New Mail Request Received",
          "You have received new mail": "You have received new mail",
          "New Contact Details": "New Contact Details",
          "We have received your request, we will respond on your issue soon":
              "We have received your request, we will respond on your issue soon:",
          "Alert!": "Alert!",
          "Contact Information Sent": "Contact Information Sent",
          "Okay": "Okay",
          "Please select driver": "Please select driver",
          "Open": "Open",
          "Closed": "Closed",
          "Something went wrong while signup":
              "Something went wrong while signup",
          "Something went wrong": "Something went wrong",
          "Verification": "Verification",
          "We have sent verification code on":
              "We have sent verification code on",
          "Verify": "Verify",
          "Password Updated": "Password Updated",
          "Password mismatch": "Password mismatch",
          "The product arrived too late": "The product arrived too late",
          "The product did not match the description":
              "The product did not match the description",
          "The purchase was fraudulent": "The purchase was fraudulent",
          "The product was damaged or defective":
              "The product was damaged or defective",
          "The merchant shipped the wrong item":
              "The merchant shipped the wrong item",
          "Wrong Item Size or Wrong Product Shipped":
              "Wrong Item Size or Wrong Product Shipped",
          "Driver arrived too late": "Driver arrived too late",
          "Driver behavior": "Driver behavior",
          "Store Vendors behavior": "Store Vendors behavior",
          "Issue with Payment Amout": "Issue with Payment Amout",
          "Others": "Others",
          "Your account is suspended": "Your account is suspended",
          "error": "error",
          "Home": "Home",
          "Work": "Work",
          "NA": "NA",
          "COD": "COD",
          "Stripe": "Stripe",
          "PayPal": "PayPal",
          "Paytm": "Paytm",
          "Razorpay": "Razorpay",
          "Instamojo": "Instamojo",
          "Paystack": "Paystack",
          "Flutterwave": "Flutterwave",
          "Accepted": "Accepted",
          "Prepared": "Prepared",
          "Delivered": "Delivered",
          "Pending Payments": "Pending Payments",
          "No Drivers Near you": "No Drivers Near you",
          "Status Updated": "Status Updated",
          "Contact": "Contact",
          "Email": "Email",
          "Call": "Call",
          "Chat": "Chat",
        },
        'hi_IN': {
          'Profile': 'प्रोफ़ाइल',
          "Your Category": "आपकी श्रेणी",
          "Your Food": "आपका खाना",
          "Edit Profile": "प्रोफ़ाइल संपादित करें",
          "Orders": "आदेश",
          "Bookings": "बुकिंग के",
          "Reviews": "समीक्षा",
          "Change password": "पासवर्ड बदलें",
          "Contact Us": "संपर्क करें",
          "Languages": "बोली",
          "Chats": "चैट",
          "About Us": "हमारे बारे में",
          "FAQs": "पूछे जाने वाले प्रश्न",
          "Terms & Conditions": "नियम एवं शर्तें",
          "Privacy Policy": "गोपनीयता नीति",
          "Help": "मदद करना",
          "Log Out": "लॉग आउट",
          "Add Admin Category": "व्यवस्थापक श्रेणी जोड़ें",
          "Cancel": "रद्द करना",
          "Submit": "प्रस्तुत करना",
          "Categories": "श्रेणियाँ",
          "Admin": "व्यवस्थापक",
          "Store": "इकट्ठा करना",
          "Are you sure": "क्या आपको यकीन है",
          "After confirming it, this category will disappear from your outlet. later you can activate it again.":
              "इसकी पुष्टि करने के बाद, यह श्रेणी आपके आउटलेट से गायब हो जाएगी। बाद में आप इसे फिर से सक्रिय कर सकते हैं।",
          "Confirm": "पुष्टि करें",
          "to delete Italian ?": "इतालवी हटाने के लिए?",
          "Delete": "मिटाना",
          "Add New!": "नया जोड़ो!",
          "Category Name": "श्रेणी नाम",
          "OK": "ठीक है",
          "Edit": "संपादन करना",
          "new": "नया",
          "Add Food": "भोजन जोड़ें",
          "Update Food": "भोजन अपडेट करें",
          "Category": "श्रेणी",
          "Food Name": "भोजन का नाम",
          "Real Price": "वास्तविक कीमत",
          "Discount Price": "डिस्काउंट मूल्य",
          "Veg": "शाकाहारी",
          "Short  description": "संक्षिप्त वर्णन",
          "Status": "दर्जा",
          "Choose From'": "से चुनें",
          "Camera": "कैमरा",
          "Gallery": "गेलरी",
          "Size?": "आकार?",
          "(Regualar,Medium,Large)": "(नियमित, मध्यम, बड़ा)",
          "Add-ons": "ऐड-ऑन",
          "(Extras,cold drinks)": "(अतिरिक्त, शीतल पेय)",
          "Update": "अद्यतन",
          "Add Store Category": "स्टोर श्रेणी जोड़ें",
          "Update  Store Category": "स्टोर श्रेणी अपडेट करें",
          "Add Category Name": "श्रेणी का नाम जोड़ें",
          "Select Category": "श्रेणी चुनना",
          "Get Orders With Dates": "तिथियों के साथ आदेश प्राप्त करें",
          "Open Time": "खुला समय",
          "Close Time": "बंद होने का समय",
          "Get Results": "परिणाम प्राप्त करें",
          "Total": "कुल",
          "Commission": "आयोग",
          "Amount Received": "रकम प्राप्त",
          "Id": "पहचान",
          "Order on": "ऑर्डर करें",
          "Items": "सामान",
          "Total Guest": "कुल अतिथि",
          "Book Date": "पुस्तक तिथि",
          "Guest Name": "अतिथि का नाम",
          "Guest Email": "अतिथि ईमेल",
          "Accept": "स्वीकार करना",
          "Reject": "अस्वीकार",
          "Complete": "पूरा",
          "Rejected": "अस्वीकृत",
          "Completed": "पूरा हुआ",
          "Full Name": "पूरा नाम",
          "Email Address": "ईमेल पता",
          "Message": "संदेश",
          "Update Cuisine": "व्यंजन अपडेट करें",
          "Select Driver": "ड्राइवर का चयन करें",
          "Restaurant Name": "रेस्टोरेंट का नाम",
          "Restaurant Address": "रेस्टोरेंट का पता",
          "Restaurant Landmark": "रेस्टोरेंट लैंडमार्क",
          "Pincode": "पिन कोड",
          "Latitude": "अक्षांश",
          "Longitute": "देशान्तर",
          "Cost For Two": "दो के लिए लागत",
          "Phone": "फ़ोन",
          "Estimate Delivery Time": "प्रसव के समय का अनुमान लगाएं",
          "Restaurant Description": "रेस्टोरेंट विवरण",
          "Select Cuisine": "व्यंजन चुनें",
          "Is Open": "खुला है",
          "Upload Your Restaurant Cover Image":
              "अपने रेस्तरां की कवर छवि अपलोड करें",
          "Upload Gallery Image": "गैलरी छवि अपलोड करें",
          "SUBMIT": "प्रस्तुत",
          "Image": "छवि",
          "Connection Failed": "कनेक्शन विफल",
          "Could not connect to network,": "नेटवर्क से कनेक्ट नहीं हो सका,",
          "Please check and try again.": "कृपया जाँच करें और पुनः प्रयास करें।",
          "retry": "पुन: प्रयास करें",
          "Foods": "फूड्स",
          "Search foods": "खाद्य पदार्थ खोजें",
          "Non Veg": "मांसाहारी",
          "Bruschetta": "ब्रुस्केटा",
          "Bruschetta is an antipasto from Italy consisting":
              "Bruschetta इटली का एक एंटीपास्टो है जिसमें शामिल है",
          "Reset Password": "पासवर्ड रीसेट",
          "Enter your email address or phone number and we will send a verification code to generate a new password":
              "अपना ईमेल पता या फोन नंबर दर्ज करें और हम एक नया पासवर्ड बनाने के लिए एक सत्यापन कोड भेजेंगे:",
          "Send OTP": "OTP भेजें",
          "Generate New Password": "नया पासवर्ड जनरेट करें",
          "New Password": "नया पासवर्ड",
          "Confirm Password": "पासवर्ड की पुष्टि कीजिये",
          "Update Password": "पासवर्ड अपडेट करें",
          "Business Insights": "व्यापार अंतर्दृष्टि",
          "Deliverd Orders": "सुपुर्दगी आदेश",
          "See More": "और देखें",
          "Today": "आज",
          "This Week :": "इस सप्ताह :",
          "This Month :": "इस महीने :",
          "Get more orders from": "से अधिक ऑर्डर प्राप्त करें",
          "Items with grocery images lead to more orders compared to items without them.Add photos to your menu items to get more orders.":
              "किराने की छवियों वाले आइटम उनके बिना आइटम की तुलना में अधिक ऑर्डर देते हैं। अधिक ऑर्डर प्राप्त करने के लिए अपने मेनू आइटम में फ़ोटो जोड़ें।",
          "Rejected Orders": "अस्वीकृत आदेश",
          "Lost sale from orders rejected by you":
              "आपके द्वारा अस्वीकृत आदेशों से बिक्री का नुकसान",
          "Improve yourself": "आपने आप को सुधारो",
          "Great Work!": "महान काम!",
          "You have some rejected and cancelled orders on your current month's stats, this will impact on your future sells, improve your self":
              "आपके चालू माह के आँकड़ों पर आपके कुछ अस्वीकृत और रद्द किए गए आदेश हैं, यह आपके भविष्य की बिक्री पर प्रभाव डालेगा, अपने आप में सुधार करेगा:",
          "You have accepted all orders till now in this month":
              "आपने इस महीने में अब तक के सभी आदेश स्वीकार कर लिए हैं",
          "Customer Complaints": "ग्राहकों की शिकायतें",
          "Details from": "से विवरण",
          "Top Items in your menu": "आपके मेनू में शीर्ष आइटम",
          "Menu items": "विकल्प सूची की चीज़ें",
          "Quantity Sold": "बेचा गया सामान",
          "Log In": "लॉग इन करें",
          "Password": "पासवर्ड",
          "Forgot Password?": "पासवर्ड भूल गए?",
          "SIGN IN": "साइन इन करें",
          "Message...": "संदेश...",
          "Order Details": "ऑर्डर का विवरण",
          "Item Total": "आइटम का कुल",
          "Taxes & charges": "कर और शुल्क",
          "Delivery Cost": "वितरण लागत",
          "Discount": "छूट",
          "Wallet Discount": "वॉलेट छूट",
          "Grand Total": "कुल योग",
          "Order ID": "आदेश ID",
          "Payment Method": "भुगतान का तरीका",
          "Delivery On": "डिलीवरी चालू",
          "Delivery To": "को सुपुर्दगी",
          "User Information": "उपयोगकर्ता के लिए जानकारी",
          "Driver Information": "चालक सूचना",
          "Update Status": "नवीनतम स्थिति",
          "Choose Status": "स्थिति चुनें",
          "Ongoing": "चल रहे",
          "New Order": "नए आदेश",
          "Ongoing Order": "जारी आदेश",
          "Past Order": "पिछला आदेश",
          "No New Orders Found": "कोई नया आदेश नहीं मिला",
          "ORDER ID :": "आदेश ID :",
          "ORDERED ON": "आदेश दिया गया",
          "TOTAL AMOUNT": "कुल राशि",
          "No Ongoing Orders Found": "कोई जारी आदेश नहीं मिला",
          "No Old Orders Found": "कोई पुराना आदेश नहीं मिला",
          "Your Reviews": "आपकी समीक्षा",
          "Products Reviews": "उत्पाद समीक्षा",
          "No Reviews Found": "कोई समीक्षा नहीं मिली",
          "No Internet Connection": "कोई इंटरनेट कनेक्शन नहीं",
          "Please wait": "कृपया प्रतीक्षा करें",
          "Chart View": "चार्ट दृश्य",
          "Orders Trends'": "आदेश रुझान'",
          "Month's distribution of your orders":
              "आपके आदेशों का महीने का वितरण",
          "Total number of orders today": "आज के आदेशों की कुल संख्या",
          "Total number of orders weekly": "साप्ताहिक आदेशों की कुल संख्या",
          "Total number of orders monthly": "मासिक आदेशों की कुल संख्या",
          "Analytics": "एनालिटिक्स",
          "Account": "खाता",
          "Available": "उपलब्ध",
          "Hide": "छिपाना",
          "No": "नहीं",
          "Yes": "हाँ",
          "Already added": "पहले से ही जोड़ा",
          "Add item to": "इसमें आइटम जोड़ें",
          "Add-ons name": "ऐड-ऑन नाम",
          "Add-ons price": "ऐड-ऑन मूल्य",
          "Ok": "ठीक",
          "Update item to": "आइटम को इसमें अपडेट करें",
          "Add Add-ons!": "ऐड-ऑन जोड़ें!",
          "Title": "शीर्षक",
          "Addon already exist with this name":
              "Addon इस नाम के साथ पहले से मौजूद है",
          "Update Add-ons! Title": "ऐड-ऑन अपडेट करें! शीर्षक",
          "Select Type": "प्रकार चुनें",
          "Only One": "केवल एक",
          "Multiple": "विभिन्न",
          "All Fields Are Required": "सभी फ़ील्ड आवश्यक हैं",
          "Successfully Add": "सफलतापूर्वक जोड़ें",
          "Successfully Updated": "सफलतापूर्वक उत्परिवर्तित",
          "Please select category": "कृपया श्रेणी चुनें",
          "Requested": "का अनुरोध किया",
          "Comlete": "पूरा करें",
          "Updating Status": "अद्यतन स्थिति",
          "Email is not valid": "विद्युतडाक मान्य नहीं है",
          "New Mail Request Received": "नया मेल अनुरोध प्राप्त हुआ",
          "You have received new mail": "आपको नया मेल प्राप्त हुआ है",
          "New Contact Details": "नया संपर्क विवरण",
          "We have received your request, we will respond on your issue soon":
              "हमें आपका अनुरोध प्राप्त हो गया है, हम जल्द ही आपके मुद्दे पर प्रतिक्रिया देंगे:",
          "Alert!": "चेतावनी!",
          "Contact Information Sent": "संपर्क जानकारी भेजी गई",
          "Okay": "ठीक",
          "Please select driver": "कृपया ड्राइवर चुनें",
          "Open": "खुला हुआ",
          "Closed": "बंद किया हुआ",
          "Something went wrong while signup": "साइन अप करते समय कुछ गलत हुआ",
          "Something went wrong": "कुछ गलत हो गया",
          "Verification": "सत्यापन",
          "We have sent verification code on": "हमने सत्यापन कोड को भेजा है",
          "Verify": "सत्यापित करना",
          "Password Updated": "पासवर्ड अपडेट किया गया",
          "Password mismatch": "पासवर्ड का मेल नहीं हुआ",
          "The product arrived too late": "उत्पाद बहुत देर से पहुंचा",
          "The product did not match the description":
              "उत्पाद विवरण से मेल नहीं खाता",
          "The purchase was fraudulent": "खरीद धोखाधड़ी थी",
          "The product was damaged or defective":
              "उत्पाद क्षतिग्रस्त या दोषपूर्ण था",
          "The merchant shipped the wrong item": "व्यापारी ने गलत वस्तु भेज दी",
          "Wrong Item Size or Wrong Product Shipped":
              "गलत आइटम का आकार या गलत उत्पाद भेज दिया गया",
          "Driver arrived too late": "ड्राइवर बहुत देर से पहुंचा",
          "Driver behavior": "चालक व्यवहार",
          "Store Vendors behavior": "स्टोर विक्रेताओं का व्यवहार",
          "Issue with Payment Amout": "भुगतान राशि के साथ समस्या",
          "Others": "अन्य",
          "Your account is suspended": "तुम्हारा खाता निलंबित है",
          "error": "गलती",
          "Home": "घर",
          "Work": "काम",
          "NA": "ना",
          "COD": "सीओडी",
          "Stripe": "पट्टी",
          "PayPal": "पेपैल",
          "Paytm": "Paytm",
          "Razorpay": "रेज़रपे",
          "Instamojo": "इंस्टामोजो",
          "Paystack": "पेस्टैक",
          "Flutterwave": "स्पंदन तरंग",
          "Accepted": "को स्वीकृत",
          "Prepared": "तैयार",
          "Delivered": "पहुंचा दिया",
          "Pending Payments": "बकाया भुगतान",
          "No Drivers Near you": "आपके आस-पास कोई ड्राइवर नहीं",
          "Status Updated": "स्थिति अपडेट",
          "Contact": "संपर्क करना",
          "Email": "ईमेल",
          "Call": "बुलाना",
          "Chat": "बात करना",
        },
        'es_DE': {
          'Profile': 'Perfil',
          "Your Category": "Tu categoría",
          "Your Food": "Tu comida",
          "Edit Profile": "Editar perfil",
          "Orders": "Pedidos",
          "Bookings": "Reservaciones",
          "Reviews": "Reseñas",
          "Change password": "Cambia la contraseña",
          "Contact Us": "Contáctenos",
          "Languages": "Idiomas",
          "Chats": "charlas",
          "About Us": "Sobre nosotros",
          "FAQs": "preguntas frecuentes",
          "Terms & Conditions": "Términos y condiciones",
          "Privacy Policy": "Política de privacidad",
          "Help": "Ayuda",
          "Log Out": "Cerrar sesión",
          "Add Admin Category": "Agregar categoría de administrador",
          "Cancel": "Cancelar",
          "Submit": "Enviar",
          "Categories": "Categorías",
          "Admin": "Administración",
          "Store": "Tienda",
          "Are you sure": "Está seguro",
          "After confirming it, this category will disappear from your outlet. later you can activate it again.":
              "Después de confirmarlo, esta categoría desaparecerá de su punto de venta. más tarde puedes activarlo de nuevo.",
          "Confirm": "Confirmar",
          "to delete Italian ?": "eliminar italiano?",
          "Delete": "Borrar",
          "Add New!": "¡Añadir nuevo!",
          "Category Name": "nombre de la categoría",
          "OK": "OK",
          "Edit": "Editar",
          "new": "nuevo",
          "Add Food": "Añadir comida",
          "Update Food": "Actualizar comida",
          "Category": "Categoría",
          "Food Name": "Nombre del alimento",
          "Real Price": "Precio real",
          "Discount Price": "Precio de descuento",
          "Veg": "verduras",
          "Short  description": "Breve descripción",
          "Status": "Estado",
          "Choose From'": "Escoge de",
          "Camera": "Cámara",
          "Gallery": "Galería",
          "Size?": "¿Tamaño?",
          "(Regualar,Medium,Large)": "(Regular, Mediano, Grande)",
          "Add-ons": "Complementos",
          "(Extras,cold drinks)": "(Extras, bebidas frías)",
          "Update": "Actualizar",
          "Add Store Category": "Agregar categoría de tienda",
          "Update  Store Category": "Actualizar categoría de tienda",
          "Add Category Name": "Agregar nombre de categoría",
          "Select Category": "selecciona una categoría",
          "Get Orders With Dates": "Obtener pedidos con fechas",
          "Open Time": "tiempo abierto",
          "Close Time": "Hora de cierre",
          "Get Results": "Tener resultados",
          "Total": "Total",
          "Commission": "Comisión",
          "Amount Received": "Cantidad recibida",
          "Id": "Identificación",
          "Order on": "ordenar en",
          "Items": "Elementos",
          "Total Guest": "Huésped Total",
          "Book Date": "Fecha del libro",
          "Guest Name": "Nombre del invitado",
          "Guest Email": "Correo electrónico de invitado",
          "Accept": "Aceptar",
          "Reject": "Rechazar",
          "Complete": "Completo",
          "Rejected": "Rechazado",
          "Completed": "Terminado",
          "Full Name": "Nombre completo",
          "Email Address": "Dirección de correo electrónico",
          "Message": "Mensaje",
          "Update Cuisine": "Actualizar cocina",
          "Select Driver": "Seleccionar conductor",
          "Restaurant Name": "Nombre del restaurante",
          "Restaurant Address": "Dirección del restaurante",
          "Restaurant Landmark": "Punto de referencia del restaurante",
          "Pincode": "Código PIN",
          "Latitude": "Latitud",
          "Longitute": "Longitud",
          "Cost For Two": "Costo para dos",
          "Phone": "Teléfono",
          "Estimate Delivery Time": "Tiempo estimado de entrega",
          "Restaurant Description": "Descripción del restaurante",
          "Select Cuisine": "Seleccionar cocina",
          "Is Open": "Esta abierto",
          "Upload Your Restaurant Cover Image":
              "Sube la imagen de portada de tu restaurante",
          "Upload Gallery Image": "Subir imagen de la galería",
          "SUBMIT": "ENVIAR",
          "Image": "Imagen",
          "Connection Failed": "La conexión falló",
          "Could not connect to network,": "No se pudo conectar a la red,",
          "Please check and try again.": "Por favor revisa e intenta de nuevo.",
          "retry": "rever",
          "Foods": "Alimentos",
          "Search foods": "Buscar alimentos",
          "Non Veg": "No vegetales",
          "Bruschetta": "Bruschetta",
          "Bruschetta is an antipasto from Italy consisting":
              "Bruschetta es un antipasto de Italia que consiste",
          "Reset Password": "Restablecer la contraseña",
          "Enter your email address or phone number and we will send a verification code to generate a new password":
              "Ingrese su dirección de correo electrónico o número de teléfono y le enviaremos un código de verificación para generar una nueva contraseña:",
          "Send OTP": "Enviar OTP",
          "Generate New Password": "Generar nueva contraseña",
          "New Password": "Nueva contraseña",
          "Confirm Password": "Confirmar contraseña",
          "Update Password": "Actualiza contraseña",
          "Business Insights": "Información empresarial",
          "Deliverd Orders": "Pedidos entregados",
          "See More": "Ver más",
          "Today": "Este Dia",
          "This Week :": "Esta semana :",
          "This Month :": "Este mes :",
          "Get more orders from": "Recibe más pedidos de",
          "Items with grocery images lead to more orders compared to items without them.Add photos to your menu items to get more orders.":
              "Los artículos con imágenes de comestibles dan lugar a más pedidos en comparación con los artículos que no las tienen. Agregue fotos a los artículos de su menú para obtener más pedidos.:",
          "Rejected Orders": "Pedidos rechazados",
          "Lost sale from orders rejected by you":
              "Venta perdida de pedidos rechazados por usted",
          "Improve yourself": "Supérate",
          "Great Work!": "¡Buen trabajo!",
          "You have some rejected and cancelled orders on your current month's stats, this will impact on your future sells, improve your self":
              "Tiene algunos pedidos rechazados y cancelados en las estadísticas de su mes actual, esto tendrá un impacto en sus ventas futuras, mejore usted mismo:",
          "You have accepted all orders till now in this month":
              "Ha aceptado todos los pedidos hasta ahora en este mes",
          "Customer Complaints": "Quejas de clientes",
          "Details from": "Detalles de",
          "Top Items in your menu": "Elementos principales en su menú",
          "Menu items": "Elementos de menú",
          "Quantity Sold": "Cantidad vendida",
          "Log In": "Iniciar sesión",
          "Password": "Clave",
          "Forgot Password?": "¿Has olvidado tu contraseña?",
          "SIGN IN": "REGISTRARSE",
          "Message...": "Mensaje...",
          "Order Details": "Detalles del pedido",
          "Item Total": "Total",
          "Taxes & charges": "Impuestos y cargos",
          "Delivery Cost": "Coste de envío",
          "Discount": "Descuento",
          "Wallet Discount": "Descuento de billetera",
          "Grand Total": "Gran total",
          "Order ID": "Solicitar ID",
          "Payment Method": "Método de pago",
          "Delivery On": "Entrega en",
          "Delivery To": "Entregar a",
          "User Information": "informacion del usuario",
          "Driver Information": "Información del conductor",
          "Update Status": "Estado de actualización",
          "Choose Status": "Elija Estado",
          "Ongoing": "En curso",
          "New Order": "Nuevo orden",
          "Ongoing Order": "Orden en curso",
          "Past Order": "Orden pasada",
          "No New Orders Found": "No se encontraron nuevos pedidos",
          "ORDER ID :": "SOLICITAR ID :",
          "ORDERED ON": "PEDIDO EL",
          "TOTAL AMOUNT": "CANTIDAD TOTAL",
          "No Ongoing Orders Found": "No se encontraron pedidos en curso",
          "No Old Orders Found": "No se encontraron pedidos antiguos",
          "Your Reviews": "Tus reseñas",
          "Products Reviews": "Reseñas de productos",
          "No Reviews Found": "No se encontraron comentarios",
          "No Internet Connection": "Sin conexión a Internet",
          "Please wait": "Espere por favor",
          "Chart View": "Vista de gráfico",
          "Orders Trends'": "Tendencias de pedidos'",
          "Month's distribution of your orders":
              "Distribución mensual de sus pedidos",
          "Total number of orders today": "Número total de pedidos hoy",
          "Total number of orders weekly": "Número total de pedidos semanales",
          "Total number of orders monthly": "Número total de pedidos mensuales",
          "Analytics": "Analítica",
          "Account": "Cuenta",
          "Available": "Disponible",
          "Hide": "Ocultar",
          "No": "No",
          "Yes": "Sí",
          "Already added": "Ya agregado",
          "Add item to": "Añadir artículo a",
          "Add-ons name": "nombre de los complementos",
          "Add-ons price": "precio de complementos",
          "Ok": "OK",
          "Update item to": "Actualizar artículo a",
          "Add Add-ons!": "¡Agregue complementos!",
          "Title": "Título",
          "Addon already exist with this name":
              "El complemento ya existe con este nombre",
          "Update Add-ons! Title": "Actualizar complementos! Título",
          "Select Type": "Seleccione tipo",
          "Only One": "Sólo uno",
          "Multiple": "Múltiple",
          "All Fields Are Required": "Todos los campos son obligatorios",
          "Successfully Add": "Añadir con éxito",
          "Successfully Updated": "Actualizado exitosamente",
          "Please select category": "Por favor seleccione categoría",
          "Requested": "Solicitado",
          "Comlete": "completo",
          "Updating Status": "Actualización de estado",
          "Email is not valid": "El correo no es válido",
          "New Mail Request Received": "Nueva solicitud de correo recibida",
          "You have received new mail": "Has recibido correo nuevo",
          "New Contact Details": "Nuevos detalles de contacto",
          "We have received your request, we will respond on your issue soon":
              "Hemos recibido tu solicitud, pronto responderemos a tu problema:",
          "Alert!": "¡Alerta!",
          "Contact Information Sent": "Información de contacto enviada",
          "Okay": "De acuerdo",
          "Please select driver": "Seleccione el controlador",
          "Open": "Abierto",
          "Closed": "Cerrado",
          "Something went wrong while signup":
              "Algo salió mal durante el registro",
          "Something went wrong": "Algo salió mal",
          "Verification": "Verificación",
          "We have sent verification code on":
              "Hemos enviado el código de verificación el",
          "Verify": "Verificar",
          "Password Updated": "Contraseña actualiza",
          "Password mismatch": "Contraseña no coincide",
          "The product arrived too late": "El producto llego demasiado tarde",
          "The product did not match the description":
              "El producto no coincidía con la descripción.",
          "The purchase was fraudulent": "La compra fue fraudulenta",
          "The product was damaged or defective":
              "El producto estaba dañado o defectuoso",
          "The merchant shipped the wrong item":
              "El comerciante envió el artículo equivocado",
          "Wrong Item Size or Wrong Product Shipped":
              "Tamaño de artículo incorrecto o producto enviado incorrecto",
          "Driver arrived too late": "El conductor llegó demasiado tarde",
          "Driver behavior": "Comportamiento del conductor",
          "Store Vendors behavior":
              "Comportamiento de los vendedores de la tienda",
          "Issue with Payment Amout": "Problema con el monto del pago",
          "Others": "Otros",
          "Your account is suspended": "Tu cuenta está suspendida",
          "error": "error",
          "Home": "Hogar",
          "Work": "Trabajar",
          "NA": "N / A",
          "COD": "BACALAO",
          "Stripe": "Raya",
          "PayPal": "Paypal",
          "Paytm": "pago",
          "Razorpay": "maquinilla de afeitar",
          "Instamojo": "Instamojo",
          "Paystack": "pila de pago",
          "Flutterwave": "Onda de aleteo",
          "Accepted": "Aceptado",
          "Prepared": "Preparado",
          "Delivered": "Entregado",
          "Pending Payments": "Pagos pendientes",
          "No Drivers Near you": "No hay conductores cerca de usted",
          "Status Updated": "Estado actualizado",
          "Contact": "Contacto",
          "Email": "Correo electrónico",
          "Call": "Llamar",
          "Chat": "Charlar",
        },
        'ar_AE': {
          'Profile': 'حساب تعريفي',
          "Your Category": "فئتك",
          "Your Food": "طعامك",
          "Edit Profile": "تعديل الملف الشخصي",
          "Orders": "الطلب #٪ s",
          "Bookings": "الحجوزات",
          "Reviews": "المراجعات",
          "Change password": "غير كلمة السر",
          "Contact Us": "اتصل بنا",
          "Languages": "اللغات",
          "Chats": "الدردشات",
          "About Us": "معلومات عنا",
          "FAQs": "أسئلة وأجوبة",
          "Terms & Conditions": "البنود و الظروف",
          "Privacy Policy": "سياسة الخصوصية",
          "Help": "مساعدة",
          "Log Out": "تسجيل خروج",
          "Add Admin Category": "إضافة فئة المسؤول",
          "Cancel": "يلغي",
          "Submit": "يُقدِّم",
          "Categories": "فئات",
          "Admin": "مسؤل",
          "Store": "متجر",
          "Are you sure": "هل أنت واثق",
          "After confirming it, this category will disappear from your outlet. later you can activate it again.":
              "بعد التأكد من ذلك ، ستختفي هذه الفئة من المنفذ الخاص بك. لاحقًا يمكنك تنشيطه مرة أخرى.",
          "Confirm": "يتأكد",
          "to delete Italian ?": "لحذف الايطالية؟",
          "Delete": "حذف",
          "Add New!": "اضف جديد!",
          "Category Name": "اسم التصنيف",
          "OK": "نعم",
          "Edit": "يحرر",
          "new": "الجديد",
          "Add Food": "أضف الطعام",
          "Update Food": "تحديث الغذاء",
          "Category": "فئة",
          "Food Name": "اسم الغذاء",
          "Real Price": "السعر الحقيقي",
          "Discount Price": "سعر الخصم",
          "Veg": "نباتي",
          "Short  description": "وصف قصير",
          "Status": "حالة",
          "Choose From'": "اختر من",
          "Camera": "آلة تصوير",
          "Gallery": "صالة عرض",
          "Size?": "بحجم؟",
          "(Regualar,Medium,Large)": "(عادي ، متوسط ​​، كبير)",
          "Add-ons": "الإضافات",
          "(Extras,cold drinks)": "(إضافات ، مشروبات باردة)",
          "Update": "تحديث",
          "Add Store Category": "أضف فئة المتجر",
          "Update  Store Category": "تحديث فئة المتجر",
          "Add Category Name": "أضف اسم الفئة",
          "Select Category": "اختر الفئة",
          "Get Orders With Dates": "احصل على الطلبات مع التمور",
          "Open Time": "وقت متاح",
          "Close Time": "وقت الاغلاق",
          "Get Results": "الحصول على النتائج",
          "Total": "المجموع",
          "Commission": "عمولة",
          "Amount Received": "تم استلام المبلغ",
          "Id": "هوية شخصية",
          "Order on": "اطلب على",
          "Items": "العناصر",
          "Total Guest": "إجمالي الضيف",
          "Book Date": "تاريخ الكتاب",
          "Guest Name": "اسم الضيف",
          "Guest Email": "البريد الإلكتروني للضيف",
          "Accept": "قبول",
          "Reject": "رفض",
          "Complete": "مكتمل",
          "Rejected": "مرفوض",
          "Completed": "مكتمل",
          "Full Name": "الاسم الكامل",
          "Email Address": "عنوان البريد الالكترونى",
          "Message": "رسالة",
          "Update Cuisine": "تحديث المطبخ",
          "Select Driver": "حدد السائق",
          "Restaurant Name": "اسم المطعم",
          "Restaurant Address": "عنوان المطعم",
          "Restaurant Landmark": "مطعم لاندمارك",
          "Pincode": "الرمز السري",
          "Latitude": "خط العرض",
          "Longitute": "طويل",
          "Cost For Two": "التكلفة لشخصين",
          "Phone": "هاتف",
          "Estimate Delivery Time": "تقدير وقت التسليم",
          "Restaurant Description": "وصف المطعم",
          "Select Cuisine": "حدد المطبخ",
          "Is Open": "مفتوح",
          "Upload Your Restaurant Cover Image":
              "قم بتحميل صورة غلاف المطعم الخاص بك",
          "Upload Gallery Image": "تحميل صورة المعرض",
          "SUBMIT": "إرسال",
          "Image": "صورة",
          "Connection Failed": "فشل الاتصال",
          "Could not connect to network,": "تعذر الاتصال بالشبكة ،",
          "Please check and try again.": "يرجى مراجعة وحاول مرة أخرى.",
          "retry": "أعد المحاولة",
          "Foods": "أغذية",
          "Search foods": "ابحث عن الأطعمة",
          "Non Veg": "غير نباتي",
          "Bruschetta": "بروشيتا",
          "Bruschetta is an antipasto from Italy consisting":
              "Bruschetta هو أنتيباستو من إيطاليا يتكون",
          "Reset Password": "إعادة تعيين كلمة المرور",
          "Enter your email address or phone number and we will send a verification code to generate a new password":
              "أدخل عنوان بريدك الإلكتروني أو رقم هاتفك وسنرسل رمز تحقق لإنشاء كلمة مرور جديدة:",
          "Send OTP": "أرسل OTP",
          "Generate New Password": "إنشاء كلمة مرور جديدة",
          "New Password": "كلمة السر الجديدة",
          "Confirm Password": "تأكيد كلمة المرور",
          "Update Password": "تطوير كلمة السر",
          "Business Insights": "رؤى الأعمال",
          "Deliverd Orders": "أوامر التسليم",
          "See More": "شاهد المزيد",
          "Today": "اليوم",
          "This Week :": "هذا الاسبوع :",
          "This Month :": "هذا الشهر :",
          "Get more orders from": "احصل على المزيد من الطلبات من",
          "Items with grocery images lead to more orders compared to items without them.Add photos to your menu items to get more orders.":
              "تؤدي العناصر التي تحتوي على صور البقالة إلى المزيد من الطلبات مقارنة بالعناصر التي لا تحتوي عليها. أضف صورًا إلى عناصر القائمة للحصول على المزيد من الطلبات:",
          "Rejected Orders": "الطلبات المرفوضة",
          "Lost sale from orders rejected by you": "خسر بيع من أوامر رفضتها",
          "Improve yourself": "طور نفسك",
          "Great Work!": "عمل عظيم!",
          "You have some rejected and cancelled orders on your current month's stats, this will impact on your future sells, improve your self":
              "لديك بعض الطلبات المرفوضة والملغاة في إحصائيات الشهر الحالي ، سيؤثر ذلك على عمليات البيع المستقبلية ، وتحسين نفسك:",
          "You have accepted all orders till now in this month":
              "لقد قبلت جميع الطلبات حتى الآن في هذا الشهر",
          "Customer Complaints": "شكاوى الزبون",
          "Details from": "التفاصيل من",
          "Top Items in your menu": "أهم العناصر في قائمتك",
          "Menu items": "عناصر القائمة",
          "Quantity Sold": "الكمية المباعة",
          "Log In": "تسجيل الدخول",
          "Password": "كلمة المرور",
          "Forgot Password?": "هل نسيت كلمة السر؟",
          "SIGN IN": "تسجيل الدخول",
          "Message...": "رسالة...",
          "Order Details": "تفاصيل الطلب",
          "Item Total": "مجموع الاشياء",
          "Taxes & charges": "الضرائب والرسوم",
          "Delivery Cost": "تكلفة التوصيل",
          "Discount": "تخفيض",
          "Wallet Discount": "خصم المحفظة",
          "Grand Total": "المبلغ الإجمالي",
          "Order ID": "رقم التعريف الخاص بالطلب",
          "Payment Method": "طريقة الدفع او السداد",
          "Delivery On": "التسليم في",
          "Delivery To": "تسليم الى",
          "User Information": "معلومات المستخدم",
          "Driver Information": "معلومات السائق",
          "Update Status": "تحديث الحالة",
          "Choose Status": "اختر الحالة",
          "Ongoing": "جاري التنفيذ",
          "New Order": "طلب جديد",
          "Ongoing Order": "طلب مستمر",
          "Past Order": "طلب سابق",
          "No New Orders Found": "لم يتم العثور على طلبات جديدة",
          "ORDER ID :": "رقم التعريف الخاص بالطلب :",
          "ORDERED ON": "تم طلبه في",
          "TOTAL AMOUNT": "المبلغ الإجمالي",
          "No Ongoing Orders Found": "لم يتم العثور على أوامر جارية",
          "No Old Orders Found": "لم يتم العثور على أوامر قديمة",
          "Your Reviews": "تعليقاتك",
          "Products Reviews": "مراجعات المنتجات",
          "No Reviews Found": "لا توجد مراجعات",
          "No Internet Connection": "لا يوجد اتصال بالإنترنت",
          "Please wait": "أرجو الإنتظار",
          "Chart View": "عرض المخطط",
          "Orders Trends'": "اتجاهات الطلبات",
          "Month's distribution of your orders": "توزيع طلباتك بالشهر",
          "Total number of orders today": "العدد الإجمالي للطلبات اليوم",
          "Total number of orders weekly": "العدد الإجمالي للطلبات أسبوعيا",
          "Total number of orders monthly": "إجمالي عدد الطلبات شهريًا",
          "Analytics": "تحليلات",
          "Account": "الحساب",
          "Available": "متوفرة",
          "Hide": "يخفي",
          "No": "رقم",
          "Yes": "نعم",
          "Already added": "تم الاضافة مسبقا",
          "Add item to": "أضف عنصرًا إلى",
          "Add-ons name": "اسم الإضافات",
          "Add-ons price": "سعر الإضافات",
          "Ok": "موافق",
          "Update item to": "تحديث العنصر إلى",
          "Add Add-ons!": "إضافة الوظائف الإضافية!",
          "Title": "عنوان",
          "Addon already exist with this name":
              "الملحق موجود بالفعل بهذا الاسم",
          "Update Add-ons! Title": "تحديث الوظائف الإضافية! عنوان",
          "Select Type": "اختر صنف",
          "Only One": "واحد فقط",
          "Multiple": "مضاعف",
          "All Fields Are Required": "جميع الحقول مطلوبة",
          "Successfully Add": "أضف بنجاح",
          "Successfully Updated": "تم التحديث بنجاح",
          "Please select category": "الرجاء تحديد الفئة",
          "Requested": "مطلوب",
          "Comlete": "كومليت",
          "Updating Status": "تحديث الحالة",
          "Email is not valid": "البريد الإلكتروني غير صالح",
          "New Mail Request Received": "تم استلام طلب بريد جديد",
          "You have received new mail": "لقد تلقيت بريدًا جديدًا",
          "New Contact Details": "تفاصيل جهة اتصال جديدة",
          "We have received your request, we will respond on your issue soon":
              "لقد تلقينا طلبك ، وسنرد على مشكلتك قريبًا:",
          "Alert!": "انذار!",
          "Contact Information Sent": "تم إرسال معلومات الاتصال",
          "Okay": "تمام",
          "Please select driver": "الرجاء تحديد سائق",
          "Open": "فتح",
          "Closed": "مغلق",
          "Something went wrong while signup": "حدث خطأ ما أثناء التسجيل",
          "Something went wrong": "هناك خطأ ما",
          "Verification": "تَحَقّق",
          "We have sent verification code on": "لقد أرسلنا رمز التحقق على",
          "Verify": "يؤكد",
          "Password Updated": "تم تحديث كلمة السر",
          "Password mismatch": "كلمة المرور غير متطابقة",
          "The product arrived too late": "وصل المنتج بعد فوات الأوان",
          "The product did not match the description":
              "المنتج لا يتطابق مع الوصف",
          "The purchase was fraudulent": "كان الشراء احتياليًا",
          "The product was damaged or defective": "المنتج تالف أو به عيب",
          "The merchant shipped the wrong item": "التاجر شحن السلعة الخاطئة",
          "Wrong Item Size or Wrong Product Shipped":
              "حجم السلعة غير صحيح أو شحن منتج خاطئ",
          "Driver arrived too late": "وصل السائق بعد فوات الأوان",
          "Driver behavior": "سلوك السائق",
          "Store Vendors behavior": "سلوك بائعي المتجر",
          "Issue with Payment Amout": "مشكلة في الدفع Amout",
          "Others": "آحرون",
          "Your account is suspended": "تم تعليق حسابك",
          "error": "خطأ",
          "Home": "مسكن",
          "Work": "عمل",
          "NA": "غير متوفر",
          "COD": "سمك القد",
          "Stripe": "شريط",
          "PayPal": "باي بال",
          "Paytm": "Paytm",
          "Razorpay": "رازورباي",
          "Instamojo": "إنستاموجو",
          "Paystack": "Paystack",
          "Flutterwave": "Flutterwave",
          "Accepted": "وافقت",
          "Prepared": "أعدت",
          "Delivered": "تم التوصيل",
          "Pending Payments": "دفعات مؤجلة",
          "No Drivers Near you": "لا يوجد سائقين بالقرب منك",
          "Status Updated": "تم تحديث الحالة",
          "Contact": "اتصال",
          "Email": "البريد الإلكتروني",
          "Call": "مكالمة",
          "Chat": "دردشة",
        },
      };
}
