/*
  Authors : initappz (Rahul Jograna)
  Website : https://initappz.com/
  App Name : Foodies Full App Flutter
  This App Template Source code is licensed as per the
  terms found in the Website https://initappz.com/license
  Copyright and Good Faith Purchasers © 2022-present initappz.
*/
import "package:get/get.dart";

class LocaleString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        "en_US": {
          "Profile": "Profile",
          "Edit": "Edit",
          "Sign In / Sign Up": "Sign In / Sign Up",
          "My Orders": "My Orders",
          "Table Booking": "Table Booking",
          "My Favorites": "My Favorites",
          "Your Address": "Your Address",
          "Wallet": "Wallet",
          "Refer & Earn": "Refer & Earn",
          "Change Password": "Change Password",
          "Languages": "Languages",
          "Chats": "Chats",
          "Contact Us": "Contact Us",
          "Help & Support": "Help & Support",
          "Frequently Asked Questions": "Frequently Asked Questions",
          "Terms & Conditions": "Terms & Conditions",
          "About Us": "About Us",
          "Log Out": "Log Out",
          "Add New Card": "Add New Card",
          "Email Address": "Email Address",
          "Card Holder Name": "Card Holder Name",
          "Card Number": "Card Number",
          "CVV": "CVV",
          "MM/YY": "MM/YY",
          "ADD CARD": "ADD CARD",
          "new": "new",
          "Add New Address": "Add New Address",
          "Update Address": "Update Address",
          "Address": "Address",
          "House / Flat No": "House / Flat No",
          "Landmark": "Landmark",
          "Zipcode": "Zipcode",
          "Optional Phone Number": "Optional Phone Number",
          "SAVE AS": "SAVE AS",
          "Home": "Home",
          "Work": "Work",
          "Other": "Other",
          "Submit": "Submit",
          "Update": "Update",
          "Initappz": "Initappz",
          "Fresh Food": "Fresh Food",
          "Lapinoz Piza": "Lapinoz Piza",
          "McDonalds": "McDonalds",
          "Checkout": "Checkout",
          "At Home": "At Home",
          "Self Pickup": "Self Pickup",
          "Delivery Address": "Delivery Address",
          "Change": "Change",
          "Store Information": "Store Information",
          "Apply Coupon Code": "Apply Coupon Code",
          "Coupon Applied :": "Coupon Applied :",
          "Available Balance": "Available Balance",
          "Item Total": "Item Total",
          "Taxes & charges": "Taxes & charges",
          "Delivery Cost": "Delivery Cost",
          "Discount": "Discount",
          "Wallet Discount": "Wallet Discount",
          "Grand Total": "Grand Total",
          "Payment Method": "Payment Method",
          "PLACE ORDER": "PLACE ORDER",
          "Access Your": "Access Your",
          "Location": "Location",
          "USE CURRENT LOCATION": "USE CURRENT LOCATION",
          "CHOOSE LOCATION": "CHOOSE LOCATION",
          "Full Name": "Full Name",
          "Message": "Message",
          "SUBMIT": "SUBMIT",
          "Coupens": "Coupens",
          "Use coupon code": "Use coupon code",
          "- Valid until": "- Valid until",
          "Apply": "Apply",
          "Cuisines": "Cuisines",
          "Repeat Order": "Repeat Order",
          "Add New": "Add New",
          "Add to cart": "Add to cart",
          "Best Deals": "Best Deals",
          "Delivered Here": "Delivered Here",
          "Edit Profile": "Edit Profile",
          "Choose From": "Choose From",
          "Camera": "Camera",
          "Gallery": "Gallery",
          "Cancel": "Cancel",
          "First Name": "First Name",
          "Last Name": "Last Name",
          "Email": "Email",
          "Mobile": "Mobile",
          "Save Profile": "Save Profile",
          "Connection Failed": "Connection Failed",
          "Could not connect to network": "Could not connect to network",
          "Please check and try again.": "Please check and try again.",
          "retry": "retry",
          "Find Location": "Find Location",
          "Search location": "Search location",
          "Use My Current Location": "Use My Current Location",
          "Confirm Location": "Confirm Location",
          "Reset Password": "Reset Password",
          "Enter your email address or phone number and we will send a verification code to generate a new password":
              "Enter your email address or phone number and we will send a verification code to generate a new password",
          "SEND": "SEND",
          "No restaurants near your location":
              "No restaurants near your location",
          "for 2": "for 2",
          "Free Delivery": "Free Delivery",
          "min": "min",
          "Ongoing orders": "Ongoing orders",
          "Past Orders": "Past Orders",
          "No New Orders Found": "No New Orders Found",
          "No Old Orders Found": "No Old Orders Found",
          "Bhairavpara, 364270": "Bhairavpara, 364270",
          "Search restaurants": "Search restaurants",
          "View All": "View All",
          "Restaurant near you": "Restaurant near you",
          "English": "English",
          "Arabic": "Arabic",
          "Hindi": "Hindi",
          "Spanish": "Spanish",
          "Log In": "Log In",
          "Password": "Password",
          "Forgot Password?": "Forgot Password?",
          "SIGN IN": "SIGN IN",
          "By Clicking Sign In you certify that you agree to our":
              "By Clicking Sign In you certify that you agree to our",
          "Privacy Policy": "Privacy Policy",
          "and": "and",
          "Terms and Condition": "Terms and Condition",
          "Or Sign In With": "Or Sign In With",
          "Google": "Google",
          "Facebook": "Facebook",
          "New user?": "New user?",
          "Sign Up": "Sign Up",
          "Hardik Rajput": "Hardik Rajput",
          "Message...": "Message...",
          "My Cart": "My Cart",
          "No Items In Cart": "No Items In Cart",
          "items": "items",
          "in your cart": "in your cart",
          "Notes": "Notes",
          "Total Price": "Total Price",
          "CHECKOUT": "CHECKOUT",
          "Update New Passsword": "Update New Passsword",
          "Generate New Password": "Generate New Password",
          "New Password": "New Password",
          "Confirm New Password": "Confirm New Password",
          "Update Password": "Update Password",
          "Order Details": "Order Details",
          "Order Number": "Order Number",
          "Payment": "Payment",
          "Delivery": "Delivery",
          "Deliver To": "Deliver To",
          "Invite Friends": "Invite Friends",
          "Create account": "Create account",
          "Please register to your account": "Please register to your account",
          "Search": "Search",
          "Start typing to search": "Start typing to search",
          "Phone Number": "Phone Number",
          "Confirm Password": "Confirm Password",
          "Referral Code (Optional)": "Referral Code (Optional)",
          "By Clicking Sign up you certify that you agree to our":
              "By Clicking Sign up you certify that you agree to our",
          "Already have an account": "Already have an account",
          "Sign In": "Sign In",
          "Browse Menu": "Browse Menu",
          "Book Table": "Book Table",
          "Delivery Time": "Delivery Time",
          "Order For 2": "Order For 2",
          "Veg": "Veg",
          "Non-veg": "Non-veg",
          "No items found!": "No items found!",
          "Price :": "Price :",
          "Add": "Add",
          "Customisable": "Customisable",
          "Items": "Items",
          "Cart": "Cart",
          "Are you sure": "Are you sure",
          "to delete Address ?": "to delete Address ?",
          "Delete": "Delete",
          "Restaurant name": "Restaurant name",
          "Recently Serched": "Recently Serched",
          "Clear": "Clear",
          "Skip": "Skip",
          "Continue": "Continue",
          "Next": "Next",
          "No Internet Connection": "No Internet Connection",
          "Please wait": "Please wait",
          "Pay With Stripe": "Pay With Stripe",
          "Expiry": "Expiry",
          "History": "History",
          "Account": "Account",
          "Selct An Offer Or Deal": "Selct An Offer Or Deal",
          "Select Date": "Select Date",
          "Select Time": "Select Time",
          "Breakfast": "Breakfast",
          "Lunch": "Lunch",
          "Dinner": "Dinner",
          "Enter Guest Detail": "Enter Guest Detail",
          "Total Guest": "Total Guest",
          "Guest Name": "Guest Name",
          "Mobile Number": "Mobile Number",
          "Email Id": "Email Id",
          "Special Request (Optional)": "Special Request (Optional)",
          "Save": "Save",
          "Table List": "Table List",
          "Toatal Guest -": "Toatal Guest -",
          "Booking Date -": "Booking Date -",
          "Guest Name -": "Guest Name -",
          "Guest Email -": "Guest Email -",
          "Guest Mobile -": "Guest Mobile -",
          "Track Order": "Track Order",
          "Verification": "Verification",
          "All Transactions": "All Transactions",
          "An 4-digit verification code has been sent to":
              "An 4-digit verification code has been sent to",
          "All fields are required": "All fields are required",
          "Card Information Saved": "Card Information Saved",
          "could not determine your location":
              "could not determine your location",
          "Successfully Added": "Successfully Added",
          "Successfully Updated": "Successfully Updated",
          "Sorry we deliver the order near to":
              "Sorry we deliver the order near to",
          "KM": "KM",
          "Please select payment method": "Please select payment method",
          "Orders once placed cannot be cancelled and non-refundable":
              "Orders once placed cannot be cancelled and non-refundable",
          "Place Order": "Place Order",
          "Thank You!": "Thank You!",
          "For Your Order": "For Your Order",
          "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.":
              "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.",
          "Track My Order": "Track My Order",
          "Back To Home": "Back To Home",
          "Featching Location": "Featching Location",
          "Location services are disabled.": "Location services are disabled.",
          "Location permissions are denied": "Location permissions are denied",
          "Location permissions are permanently denied, we cannot request permissions.":
              "Location permissions are permanently denied, we cannot request permissions.",
          "Please select offer": "Please select offer",
          "Please select size": "Please select size",
          "Profile Updated": "Profile Updated",
          "Email is not valid": "Email is not valid",
          "Your friend": "Your friend",
          "has invited you to": "has invited you to",
          "Hey Buddy download": "Hey Buddy download",
          "from app store and use my code": "from app store and use my code",
          "while sign up we both will get": "while sign up we both will get",
          "wallet amount": "wallet amount",
          "Share with buddies": "Share with buddies",
          "Copied to clipboard": "Copied to clipboard",
          "Password not match": "Password not match",
          "Getting Rewards": "Getting Rewards",
          "Congratulation": "Congratulation",
          "Close": "Close",
          "Ok": "Ok",
          "Congratulations your friend have received the":
              "Congratulations your friend have received the",
          "Congratulations you have received the":
              "Congratulations you have received the",
          "Congratulations you & your friend have received the ":
              "Congratulations you & your friend have received the ",
          "Find Food You Love": "Find Food You Love",
          "Discover the best foods from over 1,000 restaurants and fast delivery to your doorstop":
              "Discover the best foods from over 1,000 restaurants and fast delivery to your doorstop",
          "Fast Delivery": "Fast Delivery",
          "Fast delivery to your home,office wherever you are":
              "Fast delivery to your home,office wherever you are",
          "Live Tracking": "Live Tracking",
          "Real time tracking of your food on the app once you placed the order":
              "Real time tracking of your food on the app once you placed the order",
          "Are you sure?": "Are you sure?",
          "Orders once placed cannot be cancelled and are non-refundable":
              "Orders once placed cannot be cancelled and are non-refundable",
          "Yes, Place Order": "Yes, Place Order",
          "Please select card": "Please select card",
          "Creating Order": "Creating Order",
          "Your Table is successfully booked":
              "Your Table is successfully booked",
          "To Cancel this order?": "To Cancel this order?",
          "Yes": "Yes",
          "Cancel Order": "Cancel Order",
          "Order Accepted": "Order Accepted",
          "Order Prepared": "Order Prepared",
          "Order Ongoing": "Order Ongoing",
          "Order Delivered": "Order Delivered",
          "Order Cancelled": "Order Cancelled",
          "Order Rejected By Restaurant": "Order Rejected By Restaurant",
          "Order Refunded By Administrator": "Order Refunded By Administrator",
          "Payment Pending": "Payment Pending",
          "Offers": "Offers",
          "Complaints": "Complaints",
          "Issue With": "Issue With",
          "Select Store": "Select Store",
          "Select product": "Select product",
          "Select Driver": "Select Driver",
          "Select reason": "Select reason",
          "Title": "Title",
          "Brief of your issue": "Brief of your issue",
          "Comments": "Comments",
          "Write something on issue": "Write something on issue",
          "Upload Image": "Upload Image",
          "Verify your phone number": "Verify your phone number",
          "Send OTP": "Send OTP",
          "Rate Order": "Rate Order",
          "Driver Information": "Driver Information",
          "Restaurant Name": "Restaurant Name",
          "Tracking Order": "Tracking Order",
          "Order Total": "Order Total",
          "Payment Method :": "Payment Method ",
          "COD": "COD",
          "PAID": "PAID",
          "Start Location": "Start Location",
          "End Location": "End Location",
          "Your account is suspended": "Your account is suspended",
          "Something went wrong while signup":
              "Something went wrong while signup",
          "Phone Number is required": "Phone Number is required",
          "Verify": "Verify",
          "We have sent verification code on":
              "We have sent verification code on",
          "Hey there! What's up>?": "Hey there! What's up>?",
          "Nothing. Just chilling and watching youtube What about you?":
              "Nothing. Just chilling and watching youtube What about you?",
          "Same here! Been watching youtube for last 5 hours":
              "Same here! Been watching youtube for last 5 hours",
          "Yeah i know. I am in same position":
              "Yeah i know. I am in same position",
          "It's hard to be productive man": "It's hard to be productive man",
          "Sure thankyou": "Sure thankyou",
          "The product arrived too late": "The product arrived too late",
          "The product did not match the description":
              "The product did not match the description",
          "The purchase was fraudulent": "The purchase was fraudulent",
          "The product was damaged or defective":
              "The product was damaged or defective",
          "The merchant shipped the wrong item":
              "The merchant shipped the wrong item",
          "Wrong Item Size or Wrong Product Shipped":
              "Wrong Item Size or Wrong Product Shipped",
          "Driver arrived too late": "Driver arrived too late",
          "Driver behavior": "Driver behavior",
          "Store Vendors behavior": "Store Vendors behavior",
          "Issue with Payment Amount": "Issue with Payment Amount",
          "Others": "Others",
          "Order": "Order",
          "Store": "Store",
          "Driver": "Driver",
          "Product": "Product",
          "Choose Issue With": "Choose Issue With",
          "Choose Store": "Choose Store",
          "Choose Driver": "Choose Driver",
          "Choose Reason": "Choose Reason",
          "Choose Product": "Choose Product",
          "Complaints registered": "Complaints registered",
          "NA": "NA",
          "Stripe": "Stripe",
          "PayPal": "PayPal",
          "Paytm": "Paytm",
          "Razorpay": "Razorpay",
          "Instamojo": "Instamojo",
          "Paystack": "Paystack",
          "Flutterwave": "Flutterwave",
          "Requested": "Requested",
          "Accepted": "Accepted",
          "Completed": "Completed",
          "Rejected": "Rejected",
        },
        "hi_IN": {
          "Profile": "प्रोफ़ाइल",
          "Edit": "संपादन करना",
          "Sign In / Sign Up": "प्रवेश या साइन अप",
          "My Orders": "मेरे आदेश",
          "Table Booking": "टेबल बुकिंग",
          "My Favorites": "मेरे पसंदीदा",
          "Your Address": "तुम्हारा पता",
          "Wallet": "बटुआ",
          "Refer & Earn": "देखें और कमाएं",
          "Change Password": "पासवर्ड बदलें",
          "Languages": "बोली",
          "Chats": "चैट",
          "Contact Us": "संपर्क करें",
          "Help & Support": "मदद समर्थन",
          "Frequently Asked Questions": "अधिकतर पूछे जाने वाले सवाल",
          "Terms & Conditions": "नियम एवं शर्तें",
          "About Us": "हमारे बारे में",
          "Log Out": "लॉग आउट",
          "Add New Card": "नया कार्ड जोड़ें,",
          "Email Address": "ईमेल पता",
          "Card Holder Name": "कार्डधारक का नाम",
          "Card Number": "कार्ड नंबर",
          "CVV": "सीवीवी",
          "MM/YY": "महीना साल",
          "ADD CARD": "कार्ड जोड़ें",
          "new": "नया",
          "Add New Address": "नया पता जोड़ें",
          "Update Address": "पता अपडेट करें",
          "Address": "पता",
          "House / Flat No": "मकान/फ्लैट नं",
          "Landmark": "सीमाचिह्न",
          "Zipcode": "पिन कोड",
          "Optional Phone Number": "वैकल्पिक फोन नंबर",
          "SAVE AS": "के रूप रक्षित करें",
          "Home": "घर",
          "Work": "काम",
          "Other": "अन्य",
          "Submit": "प्रस्तुत करना",
          "Update": "अद्यतन",
          "Initappz": "इनिटैप्ज़",
          "Fresh Food": "ताजा खाना",
          "Lapinoz Piza": "ला पिनोज़ पिज्जा",
          "McDonalds": "McDonalds",
          "Checkout": "चेक आउट",
          "At Home": "घर पर",
          "Self Pickup": "स्व चयन",
          "Delivery Address": "डिलिवरी का पता",
          "Change": "परिवर्तन",
          "Store Information": "जानकारी जमा करो",
          "Apply Coupon Code": "कूपन कोड लागू करें",
          "Coupon Applied :": "कूपन लागू:",
          "Available Balance": "उपलब्ध शेष राशि",
          "Item Total": "आइटम का कुल",
          "Taxes & charges": "कर और शुल्क",
          "Delivery Cost": "वितरण लागत",
          "Discount": "छूट",
          "Wallet Discount": "वॉलेट छूट",
          "Grand Total": "कुल योग",
          "Payment Method": "भुगतान का तरीका",
          "PLACE ORDER": "आदेश देना",
          "Access Your": "अपना प्रवेश करें",
          "Location": "स्थान",
          "USE CURRENT LOCATION": "वर्तमान स्थान का उपयोग करें",
          "CHOOSE LOCATION": "स्थान का चयन",
          "Full Name": "पूरा नाम",
          "Message": "संदेश",
          "SUBMIT": "प्रस्तुत",
          "Coupens": "कूपन",
          "Use coupon code": "कूपन कोड का प्रयोग करें",
          "- Valid until": "- तब तक वैध",
          "Apply": "आवेदन करना",
          "Cuisines": "व्यंजनों",
          "Repeat Order": "दुबारा ऑर्डर",
          "Add New": "नया जोड़ो",
          "Add to cart": "कार्ट में जोड़ें",
          "Best Deals": "सबसे अच्छे सौदे",
          "Delivered Here": "यहां दिया गया",
          "Edit Profile": "प्रोफ़ाइल संपादित करें",
          "Choose From": "से चुनें",
          "Camera": "कैमरा",
          "Gallery": "गेलरी",
          "Cancel": "रद्द करना",
          "First Name": "पहला नाम",
          "Last Name": "उपनाम",
          "Email": "ईमेल",
          "Mobile": "गतिमान",
          "Save Profile": "प्रोफ़ाइल बचा",
          "Connection Failed": "कनेक्शन विफल",
          "Could not connect to network": "नेटवर्क से कनेक्ट नहीं हो सका",
          "Please check and try again.": "कृपया जाँच करें और पुनः प्रयास करें.",
          "retry": "पुन: प्रयास करें",
          "Find Location": "स्थान खोजें",
          "Search location": "स्थान खोजें",
          "Use My Current Location": "मेरे वर्तमान स्थान का उपयोग करें",
          "Confirm Location": "स्थान की पुष्टि करें",
          "Reset Password": "पासवर्ड रीसेट",
          "Enter your email address or phone number and we will send a verification code to generate a new password":
              "अपना ईमेल पता या फोन नंबर दर्ज करें और हम एक नया पासवर्ड बनाने के लिए एक सत्यापन कोड भेजेंगे",
          "SEND": "भेजना",
          "No restaurants near your location":
              "आपके स्थान के पास कोई रेस्तरां नहीं है",
          "for 2": "2 के लिए",
          "Free Delivery": "नि: शुल्क डिलिवरी",
          "min": "मिनट",
          "Ongoing orders": "चल रहे आदेश",
          "Past Orders": "पिछले आदेश",
          "No New Orders Found": "कोई नया आदेश नहीं मिला",
          "No Old Orders Found": "कोई पुराना आदेश नहीं मिला",
          "Bhairavpara, 364270": "भैरवपरा, 364270",
          "Search restaurants": "रेस्तरां खोजें",
          "View All": "सभी को देखें",
          "Restaurant near you": "आपके पास रेस्टोरेंट",
          "English": "अंग्रेज़ी",
          "Arabic": "अरबी",
          "Hindi": "हिन्दी",
          "Spanish": "स्पैनिश",
          "Log In": "लॉग इन करें",
          "Password": "पासवर्ड",
          "Forgot Password?": "पासवर्ड भूल गए?",
          "SIGN IN": "साइन इन करें",
          "By Clicking Sign In you certify that you agree to our":
              "साइन इन पर क्लिक करके आप प्रमाणित करते हैं कि आप हमारी बात से सहमत हैं",
          "Privacy Policy": "गोपनीयता नीति",
          "and": "तथा",
          "Terms and Condition": "नियम व शर्तें",
          "Or Sign In With": "या इसके साथ साइन इन करें",
          "Google": "गूगल",
          "Facebook": "फेसबुक",
          "New user?": "नया उपयोगकर्ता?",
          "Sign Up": "साइन अप करें",
          "Hardik Rajput": "हार्दिक राजपूत",
          "Message...": "संदेश...",
          "My Cart": "मेरी गाड़ी",
          "No Items In Cart": "कार्ट में कोई आइटम नहीं",
          "items": "सामान",
          "in your cart": "आपके कार्ट में",
          "Notes": "टिप्पणियाँ",
          "Total Price": "कुल कीमत",
          "CHECKOUT": "चेक आउट",
          "Update New Passsword": "नया पासवर्ड अपडेट करें",
          "Generate New Password": "नया पासवर्ड जनरेट करें",
          "New Password": "नया पासवर्ड",
          "Confirm New Password": "नए पासवर्ड की पुष्टि करें",
          "Update Password": "पासवर्ड अपडेट करें",
          "Order Details": "ऑर्डर का विवरण",
          "Order Number": "क्रम संख्या",
          "Payment": "भुगतान",
          "Delivery": "वितरण",
          "Deliver To": "उसे देदो",
          "Invite Friends": "मित्रों को आमंत्रित करें",
          "Create account": "खाता बनाएं",
          "Please register to your account": "कृपया अपने खाते में पंजीकरण करें",
          "Search": "खोज",
          "Start typing to search": "खोजने के लिए टाइप करना प्रारंभ करें",
          "Phone Number": "फ़ोन नंबर",
          "Confirm Password": "पासवर्ड की पुष्टि कीजिये",
          "Referral Code (Optional)": "रेफरल कोड (वैकल्पिक)",
          "By Clicking Sign up you certify that you agree to our":
              "साइन अप पर क्लिक करके आप प्रमाणित करते हैं कि आप हमारी बात से सहमत हैं",
          "Already have an account": "क्या आपके पास पहले से एक खाता मौजूद है",
          "Sign In": "साइन इन करें",
          "Browse Menu": "मेनू ब्राउज़ करें",
          "Book Table": "टेबल बुक करें",
          "Delivery Time": "डिलीवरी का समय",
          "Order For 2": "2 के लिए आदेश",
          "Veg": "शाकाहारी",
          "Non-veg": "मांसाहारी",
          "No items found!": "कुछ नहीं मिला!",
          "Price :": "कीमत :",
          "Add": "जोड़ें",
          "Customisable": "अनुकूलन",
          "Items": "सामान",
          "Cart": "कार्ट",
          "Are you sure": "क्या आपको यकीन है",
          "to delete Address ?": "पता मिटाने के लिए ?",
          "Delete": "मिटाना",
          "Restaurant name": "रेस्टोरेंट का नाम",
          "Recently Serched": "हाल ही में खोजा गया",
          "Clear": "साफ़",
          "Skip": "छोड़ें",
          "Continue": "जारी रखना",
          "Next": "अगला",
          "No Internet Connection": "कोई इंटरनेट कनेक्शन नहीं",
          "Please wait": "कृपया प्रतीक्षा करें",
          "Pay With Stripe": "स्ट्राइप के साथ भुगतान करें",
          "Expiry": "समाप्ति",
          "History": "इतिहास",
          "Account": "खाता",
          "Selct An Offer Or Deal": "एक ऑफ़र या डील चुनें",
          "Select Date": "तारीख़ चुनें",
          "Select Time": "समय चुनें",
          "Breakfast": "नाश्ता",
          "Lunch": "दिन का खाना",
          "Dinner": "रात का खाना",
          "Enter Guest Detail": "अतिथि विवरण दर्ज करें",
          "Total Guest": "कुल अतिथि",
          "Guest Name": "अतिथि का नाम",
          "Mobile Number": "मोबाइल नंबर",
          "Email Id": "ईमेल आईडी",
          "Special Request (Optional)": "विशेष अनुरोध (वैकल्पिक)",
          "Save": "बचाना",
          "Table List": "तालिका सूची",
          "Toatal Guest -": "कुल अतिथि -",
          "Booking Date -": "बुक करने की तिथि -",
          "Guest Name -": "अतिथि का नाम -",
          "Guest Email -": "अतिथि ईमेल -",
          "Guest Mobile -": "अतिथि मोबाइल -",
          "Track Order": "ऑर्डर पर नज़र रखें",
          "Verification": "सत्यापन",
          "All Transactions": "सभी लेन - देन",
          "An 4-digit verification code has been sent to":
              "4 अंकों का सत्यापन कोड . को भेज दिया गया है",
          "All fields are required": "सभी फ़ील्ड आवश्यक हैं",
          "Card Information Saved": "कार्ड की जानकारी सहेजी गई",
          "could not determine your location":
              "आपका स्थान निर्धारित नहीं कर सका",
          "Successfully Added": "सफलतापूर्वक शामिल",
          "Successfully Updated": "सफलतापूर्वक उत्परिवर्तित",
          "Sorry we deliver the order near to":
              "क्षमा करें, हम ऑर्डर को निकट पहुंचाते हैं",
          "KM": "किमी",
          "Please select payment method": "कृपया भुगतान विधि चुनें",
          "Orders once placed cannot be cancelled and non-refundable":
              "एक बार दिए गए आदेश को रद्द नहीं किया जा सकता और वापस नहीं किया जा सकता",
          "Place Order": "आदेश देना",
          "Thank You!": "धन्यवाद!",
          "For Your Order": "आपके आदेश के लिए",
          "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.":
              "यह एक लंबे समय से स्थापित तथ्य है कि एक पाठक किसी पृष्ठ की पठनीय सामग्री से उसके लेआउट को देखते हुए विचलित हो जाएगा।",
          "Track My Order": "मेरा आदेश खोजें",
          "Back To Home": "घर वापिस जा रहा हूँ",
          "Featching Location": "स्थान प्राप्त करना",
          "Location services are disabled.": "स्थान सेवाएं अक्षम हैं।",
          "Location permissions are denied":
              "स्थान अनुमतियां अस्वीकार कर दी गई हैं",
          "Location permissions are permanently denied, we cannot request permissions.":
              "स्थान अनुमतियों को स्थायी रूप से अस्वीकार कर दिया गया है, हम अनुमतियों का अनुरोध नहीं कर सकते।",
          "Please select offer": "कृपया ऑफ़र चुनें",
          "Please select size": "कृपया आकार का चयन करें",
          "Profile Updated": "प्रोफाइल अद्यतन किया गया",
          "Email is not valid": "विद्युतडाक मान्य नहीं है",
          "Your friend": "आपके दोस्त",
          "has invited you to": "आपको आमंत्रित किया है",
          "Hey Buddy download": "अरे बडी डाउनलोड",
          "from app store and use my code":
              "ऐप स्टोर से और मेरे कोड का उपयोग करें",
          "while sign up we both will get":
              "साइन अप करते समय हम दोनों को मिलेगा",
          "wallet amount": "बटुआ राशि",
          "Share with buddies": "दोस्तों के साथ शेयर करें",
          "Copied to clipboard": "क्लिपबोर्ड पर नकल",
          "Password not match": "पासवर्ड मेल नहीं खाता",
          "Getting Rewards": "पुरस्कार प्राप्त करना",
          "Congratulation": "बधाई",
          "Close": "बंद करना",
          "Ok": "ठीक",
          "Congratulations your friend have received the":
              "बधाई हो आपके मित्र को मिल गया है",
          "Congratulations you have received the": "बधाई हो आपको मिली है",
          "Congratulations you & your friend have received the ":
              "बधाई हो आपको और आपके मित्र ने प्राप्त किया है",
          "Find Food You Love": "आप जो खाना पसंद करते हैं उसे ढूंढें",
          "Discover the best foods from over 1,000 restaurants and fast delivery to your doorstop":
              "1,000 से अधिक रेस्तरां से सर्वोत्तम खाद्य पदार्थों की खोज करें और अपने दरवाजे पर तेजी से वितरण करें",
          "Fast Delivery": "तेजी से वितरण",
          "Fast delivery to your home,office wherever you are":
              "आप कहीं भी हों, अपने घर, कार्यालय में तेजी से वितरण करें",
          "Live Tracking": "लाइव ट्रैकिंग",
          "Real time tracking of your food on the app once you placed the order":
              "ऑर्डर देने के बाद ऐप पर अपने भोजन की रीयल टाइम ट्रैकिंग",
          "Are you sure?": "क्या आपको यकीन है?",
          "Orders once placed cannot be cancelled and are non-refundable":
              "एक बार दिए गए आदेश रद्द नहीं किए जा सकते हैं और अप्रतिदेय हैं",
          "Yes, Place Order": "हां, ऑर्डर दें",
          "Please select card": "कृपया कार्ड चुनें",
          "Creating Order": "आदेश बनाना",
          "Your Table is successfully booked":
              "आपकी तालिका सफलतापूर्वक बुक हो गई है",
          "To Cancel this order?": "इस आदेश को रद्द करने के लिए?",
          "Yes": "हाँ",
          "Cancel Order": "आदेश रद्द",
          "Order Accepted": "आदेश स्वीकृत",
          "Order Prepared": "आदेश तैयार",
          "Order Ongoing": "आदेश जारी है",
          "Order Delivered": "आदेश दिया गया",
          "Order Cancelled": "आदेश रद्द किया गया",
          "Order Rejected By Restaurant": "रेस्तरां द्वारा आदेश अस्वीकृत",
          "Order Refunded By Administrator":
              "व्यवस्थापक द्वारा वापस किया गया आदेश",
          "Payment Pending": "भुगतान लंबित",
          "Offers": "ऑफर",
          "Complaints": "शिकायतों",
          "Issue With": "मुद्दे के साथ",
          "Select Store": "स्टोर चुनें",
          "Select product": "उत्पाद चुनें",
          "Select Driver": "ड्राइवर का चयन करें",
          "Select reason": "कारण चुनें",
          "Title": "शीर्षक",
          "Brief of your issue": "आपकी समस्या का संक्षिप्त विवरण",
          "Comments": "टिप्पणियाँ",
          "Write something on issue": "मुद्दे पर कुछ लिखें",
          "Upload Image": "तस्विर अपलोड करना",
          "Verify your phone number": "अपना फोन नम्बर सत्यापित करें",
          "Send OTP": "OTP भेजें",
          "Rate Order": "दर आदेश",
          "Driver Information": "चालक सूचना",
          "Restaurant Name": "रेस्टोरेंट का नाम",
          "Tracking Order": "ट्रैकिंग आदेश",
          "Order Total": "कुल आर्डर",
          "Payment Method :": "भुगतान का तरीका",
          "COD": "सीओडी",
          "PAID": "भुगतान किया है",
          "Start Location": "प्रारंभ स्थान",
          "End Location": "अंतिम स्थान",
          "Your account is suspended": "तुम्हारा खाता निलंबित है",
          "Something went wrong while signup": "साइन अप करते समय कुछ गलत हुआ",
          "Phone Number is required": "फ़ोन नंबर आवश्यक है",
          "Verify": "सत्यापित करना",
          "We have sent verification code on": "हमने सत्यापन कोड को भेजा है",
          "Hey there! What's up>?": "सुनो! क्या चल रहा है>?",
          "Nothing. Just chilling and watching youtube What about you?":
              "कुछ भी तो नहीं। बस चिल करना और youtube देखना आपके बारे में क्या?",
          "Same here! Been watching youtube for last 5 hours":
              "यहाँ भी ऐसा ही! पिछले 5 घंटे से youtube देख रहा हूँ",
          "Yeah i know. I am in same position":
              "हाँ मुझे पता हे। मैं एक ही स्थिति में हूँ",
          "It's hard to be productive man": "उत्पादक आदमी बनना कठिन है",
          "Sure thankyou": "पक्का, आपका धन्यवाद",
          "The product arrived too late": "उत्पाद बहुत देर से पहुंचा",
          "The product did not match the description":
              "उत्पाद विवरण से मेल नहीं खाता",
          "The purchase was fraudulent": "खरीद धोखाधड़ी थी",
          "The product was damaged or defective":
              "उत्पाद क्षतिग्रस्त या दोषपूर्ण था",
          "The merchant shipped the wrong item": "व्यापारी ने गलत वस्तु भेज दी",
          "Wrong Item Size or Wrong Product Shipped":
              "गलत आइटम का आकार या गलत उत्पाद भेज दिया गया",
          "Driver arrived too late": "ड्राइवर बहुत देर से पहुंचा",
          "Driver behavior": "चालक व्यवहार",
          "Store Vendors behavior": "स्टोर विक्रेताओं का व्यवहार",
          "Issue with Payment Amount": "भुगतान राशि के साथ समस्या",
          "Others": "अन्य",
          "Order": "आदेश",
          "Store": "इकट्ठा करना",
          "Driver": "चालक",
          "Product": "उत्पाद",
          "Choose Issue With": "के साथ समस्या चुनें",
          "Choose Store": "स्टोर चुनें",
          "Choose Driver": "ड्राइवर चुनें",
          "Choose Reason": "कारण चुनें",
          "Choose Product": "उत्पाद चुनें",
          "Complaints registered": "शिकायतें दर्ज",
          "NA": "ना",
          "Stripe": "पट्टी",
          "PayPal": "पेपैल",
          "Paytm": "Paytm",
          "Razorpay": "रेज़रपे",
          "Instamojo": "इंस्टामोजो",
          "Paystack": "पेस्टैक",
          "Flutterwave": "स्पंदन तरंग",
          "Requested": "का अनुरोध किया",
          "Accepted": "को स्वीकृत",
          "Completed": "पूरा हुआ",
          "Rejected": "अस्वीकृत",
        },
        "es_DE": {
          "Profile": "Profile",
          "Edit": "Editar",
          "Sign In / Sign Up": "Iniciar sesión, crear cuenta",
          "My Orders": "Mis ordenes",
          "Table Booking": "Reserva de mesa",
          "My Favorites": "Mis favoritas",
          "Your Address": "Su dirección",
          "Wallet": "Cartera",
          "Refer & Earn": "Referir y ganar",
          "Change Password": "Cambia la contraseña",
          "Languages": "Idiomas",
          "Chats": "charlas",
          "Contact Us": "Contacta con nosotras",
          "Help & Support": "Servicio de asistencia",
          "Frequently Asked Questions": "Preguntas frecuentes",
          "Terms & Conditions": "Términos y condiciones",
          "About Us": "Sobre nosotros",
          "Log Out": "Cerrar sesión",
          "Add New Card": "Agregar nueva tarjeta",
          "Email Address": "Dirección de correo electrónico",
          "Card Holder Name": "Nombre del titular de la tarjeta",
          "Card Number": "número de tarjeta",
          "CVV": "CVV",
          "MM/YY": "MM/AA",
          "ADD CARD": "AGREGAR TARJETA",
          "new": "nueva",
          "Add New Address": "Agregar nueva dirección",
          "Update Address": "Actualizar dirección",
          "Address": "Dirección",
          "House / Flat No": "Casa / Piso No",
          "Landmark": "Punto de referencia",
          "Zipcode": "Código postal",
          "Optional Phone Number": "Número de teléfono opcional",
          "SAVE AS": "GUARDAR COMO",
          "Home": "Hogar",
          "Work": "Trabajar",
          "Other": "Otra",
          "Submit": "Enviar",
          "Update": "Actualizar",
          "Initappz": "Initappz",
          "Fresh Food": "Comida fresca",
          "Lapinoz Piza": "Pizzería La Pinoz",
          "McDonalds": "McDonalds",
          "Checkout": "Verificar",
          "At Home": "En casa",
          "Self Pickup": "Recogerse",
          "Delivery Address": "Dirección de entrega",
          "Change": "Cambio",
          "Store Information": "Almacenar información",
          "Apply Coupon Code": "Aplicar código de cupón",
          "Coupon Applied :": "Cupón aplicado :",
          "Available Balance": "Saldo disponible",
          "Item Total": "Total",
          "Taxes & charges": "Impuestos y cargos",
          "Delivery Cost": "Coste de envío",
          "Discount": "Descuento",
          "Wallet Discount": "Descuento de billetera",
          "Grand Total": "Gran total",
          "Payment Method": "Método de pago",
          "PLACE ORDER": "REALIZAR PEDIDO",
          "Access Your": "Accede a tu",
          "Location": "Ubicación",
          "USE CURRENT LOCATION": "UTILIZAR UBICACIÓN ACTUAL",
          "CHOOSE LOCATION": "ELEGIR LA UBICACIÓN",
          "Full Name": "Nombre completo",
          "Message": "Mensaje",
          "SUBMIT": "ENVIAR",
          "Coupens": "cupones",
          "Use coupon code": "Usar código de cupón",
          "- Valid until": "- Válido hasta",
          "Apply": "Aplicar",
          "Cuisines": "Cocinas",
          "Repeat Order": "Repite la orden",
          "Add New": "Agregar nueva",
          "Add to cart": "Añadir a la cesta",
          "Best Deals": "Mejores tratos",
          "Delivered Here": "Entregado aquí",
          "Edit Profile": "Editar perfil",
          "Choose From": "Escoge de",
          "Camera": "Cámara",
          "Gallery": "Galería",
          "Cancel": "Cancelar",
          "First Name": "Primer nombre",
          "Last Name": "Apellido",
          "Email": "Correo electrónico",
          "Mobile": "Móvil",
          "Save Profile": "Guardar perfil",
          "Connection Failed": "La conexión falló",
          "Could not connect to network": "No se pudo conectar a la red",
          "Please check and try again.": "Por favor revisa e intenta de nuevo.",
          "retry": "rever",
          "Find Location": "Encontrar ubicacion",
          "Search location": "Buscar ubicación",
          "Use My Current Location": "Usar mi ubicación actual",
          "Confirm Location": "Confirmar ubicación",
          "Reset Password": "Restablecer la contraseña",
          "Enter your email address or phone number and we will send a verification code to generate a new password":
              "Ingrese su dirección de correo electrónico o número de teléfono y le enviaremos un código de verificación para generar una nueva contraseña",
          "SEND": "ENVIAR",
          "No restaurants near your location":
              "No hay restaurantes cerca de tu ubicación",
          "for 2": "para 2",
          "Free Delivery": "Entrega gratis",
          "min": "min",
          "Ongoing orders": "pedidos en curso",
          "Past Orders": "Pedidos anteriores",
          "No New Orders Found": "No se han encontrado nuevos pedidos",
          "No Old Orders Found": "No se encontraron pedidos antiguos",
          "Bhairavpara, 364270": "Bhairavpara, 364270",
          "Search restaurants": "Buscar restaurantes",
          "View All": "Ver todo",
          "Restaurant near you": "Restaurante cerca de ti",
          "English": "Inglesa",
          "Arabic": "Arábica",
          "Hindi": "hindi",
          "Spanish": "Española",
          "Log In": "Iniciar sesión",
          "Password": "Clave",
          "Forgot Password?": "¿Has olvidado tu contraseña?",
          "SIGN IN": "REGISTRARSE",
          "By Clicking Sign In you certify that you agree to our":
              "Al hacer clic en Iniciar sesión, certifica que está de acuerdo con nuestra",
          "Privacy Policy": "Política de privacidad",
          "and": "y",
          "Terms and Condition": "Términos y Condiciones",
          "Or Sign In With": "O inicia sesión con",
          "Google": "Google",
          "Facebook": "Facebook",
          "New user?": "¿Nueva usuaria?",
          "Sign Up": "Inscribirse",
          "Hardik Rajput": "Hardik Rajput",
          "Message...": "Mensaje...",
          "My Cart": "Mi carrito",
          "No Items In Cart": "No hay artículos en el carrito",
          "items": "elementos",
          "in your cart": "en tu carrito",
          "Notes": "notas",
          "Total Price": "Precio total",
          "CHECKOUT": "VERIFICAR",
          "Update New Passsword": "Actualizar nueva contraseña",
          "Generate New Password": "Generar nueva contraseña",
          "New Password": "Nueva contraseña",
          "Confirm New Password": "Confirmar nueva contraseña",
          "Update Password": "Actualiza contraseña",
          "Order Details": "Detalles del pedido",
          "Order Number": "Número de orden",
          "Payment": "Pago",
          "Delivery": "Entrega",
          "Deliver To": "Entregar a",
          "Invite Friends": "Invitar a amigas",
          "Create account": "Crear una cuenta",
          "Please register to your account":
              "Por favor regístrese en su cuenta",
          "Search": "Búsqueda",
          "Start typing to search": "Empieza a escribir para buscar",
          "Phone Number": "Número de teléfono",
          "Confirm Password": "Confirmar contraseña",
          "Referral Code (Optional)": "Código de Referencia (Opcional)",
          "By Clicking Sign up you certify that you agree to our":
              "Al hacer clic en Registrarse certifica que está de acuerdo con nuestra",
          "Already have an account": "Ya tienes una cuenta",
          "Sign In": "Registrarse",
          "Browse Menu": "Navegar menú",
          "Book Table": "Mesa de libros",
          "Delivery Time": "El tiempo de entrega",
          "Order For 2": "orden para 2",
          "Veg": "verduras",
          "Non-veg": "No vegetales",
          "No items found!": "¡No se encontraron artículos!",
          "Price :": "Precio :",
          "Add": "Agregar",
          "Customisable": "personalizable",
          "Items": "Elementos",
          "Cart": "Carro",
          "Are you sure": "Estas segura",
          "to delete Address ?": "eliminar la dirección?",
          "Delete": "Borrar",
          "Restaurant name": "Nombre del restaurante",
          "Recently Serched": "Recientemente buscada",
          "Clear": "Claro",
          "Skip": "Saltar",
          "Continue": "Continuar",
          "Next": "Próximo",
          "No Internet Connection": "Sin conexión a Internet",
          "Please wait": "Espere por favor",
          "Pay With Stripe": "Pagar con raya",
          "Expiry": "Expiración",
          "History": "Historia",
          "Account": "Cuenta",
          "Selct An Offer Or Deal": "Seleccione una oferta o trato",
          "Select Date": "Seleccione fecha",
          "Select Time": "Seleccionar hora",
          "Breakfast": "Desayuno",
          "Lunch": "Almuerza",
          "Dinner": "Cena",
          "Enter Guest Detail": "Ingrese los detalles del huésped",
          "Total Guest": "Invitado total",
          "Guest Name": "Nombre del invitado",
          "Mobile Number": "Número de teléfono móvil",
          "Email Id": "Identificación de correo",
          "Special Request (Optional)": "Solicitud Especial (Opcional)",
          "Save": "Ahorrar",
          "Table List": "Lista de tablas",
          "Toatal Guest -": "Invitado total -",
          "Booking Date -": "Fecha para registrarse -",
          "Guest Name -": "Nombre del invitado -",
          "Guest Email -": "Correo electrónico de invitado -",
          "Guest Mobile -": "Invitada móvil -",
          "Track Order": "Orden de pista",
          "Verification": "Verificación",
          "All Transactions": "Todas las transacciones",
          "An 4-digit verification code has been sent to":
              "Se ha enviado un código de verificación de 4 dígitos a",
          "All fields are required": "Todos los campos son obligatorios",
          "Card Information Saved": "Información de la tarjeta guardada",
          "could not determine your location":
              "no se pudo determinar su ubicación",
          "Successfully Added": "Añadido exitosamente",
          "Successfully Updated": "Actualizado exitosamente",
          "Sorry we deliver the order near to":
              "Lo sentimos, entregamos el pedido cerca de",
          "KM": "kilómetros",
          "Please select payment method":
              "Por favor seleccione el método de pago",
          "Orders once placed cannot be cancelled and non-refundable":
              "Los pedidos una vez realizados no se pueden cancelar y no son reembolsables",
          "Place Order": "Realizar pedido",
          "Thank You!": "¡Gracias!",
          "For Your Order": "Para su pedido",
          "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.":
              "Es un hecho establecido desde hace mucho tiempo que un lector se distraerá con el contenido legible de una página cuando mire su diseño.",
          "Track My Order": "Seguimiento de mi pedido",
          "Back To Home": "De vuelta a casa",
          "Featching Location": "Obtener ubicación",
          "Location services are disabled.":
              "Los servicios de ubicación están deshabilitados.",
          "Location permissions are denied":
              "Los permisos de ubicación están denegados",
          "Location permissions are permanently denied, we cannot request permissions.":
              "Los permisos de ubicación se niegan permanentemente, no podemos solicitar permisos.",
          "Please select offer": "Por favor seleccione oferta",
          "Please select size": "Por favor seleccione un tamaño",
          "Profile Updated": "Perfil actualizado",
          "Email is not valid": "El correo no es válido",
          "Your friend": "Tu amigo",
          "has invited you to": "te ha invitado a",
          "Hey Buddy download": "Hola amigo descargar",
          "from app store and use my code":
              "de la tienda de aplicaciones y usa mi código",
          "while sign up we both will get":
              "mientras te registras ambos conseguiremos",
          "wallet amount": "monto de la billetera",
          "Share with buddies": "compartir con amigos",
          "Copied to clipboard": "Copiado al portapapeles",
          "Password not match": "La contraseña no coincide",
          "Getting Rewards": "Obtener recompensas",
          "Congratulation": "Felicitaciones",
          "Close": "Cerca",
          "Ok": "Ok",
          "Congratulations your friend have received the":
              "Enhorabuena, tu amigo ha recibido el",
          "Congratulations you have received the":
              "Felicidades has recibido el",
          "Congratulations you & your friend have received the ":
              "Felicitaciones, usted y su amigo han recibido el ",
          "Find Food You Love": "Encuentra la comida que te gusta",
          "Discover the best foods from over 1,000 restaurants and fast delivery to your doorstop":
              "Descubra los mejores alimentos de más de 1,000 restaurantes y entrega rápida a su puerta",
          "Fast Delivery": "Entrega rápida",
          "Fast delivery to your home,office wherever you are":
              "Entrega rápida a su hogar, oficina donde quiera que esté",
          "Live Tracking": "Seguimiento en vivo",
          "Real time tracking of your food on the app once you placed the order":
              "Seguimiento en tiempo real de su comida en la aplicación una vez que realizó el pedido",
          "Are you sure?": "Estas seguro",
          "Orders once placed cannot be cancelled and are non-refundable":
              "Los pedidos una vez realizados no se pueden cancelar y no son reembolsables",
          "Yes, Place Order": "Sí, realizar pedido",
          "Please select card": "Por favor, seleccione la tarjeta",
          "Creating Order": "Creando orden",
          "Your Table is successfully booked":
              "Su mesa está reservada con éxito",
          "To Cancel this order?": "¿Cancelar este pedido?",
          "Yes": "Sí",
          "Cancel Order": "Cancelar orden",
          "Order Accepted": "Pedido Aceptado",
          "Order Prepared": "Pedido Preparado",
          "Order Ongoing": "Pedido en curso",
          "Order Delivered": "Pedido Entregado",
          "Order Cancelled": "Pedido Cancelado",
          "Order Rejected By Restaurant": "Pedido rechazado por el restaurante",
          "Order Refunded By Administrator":
              "Pedido reembolsado por el administrador",
          "Payment Pending": "Pago Pendiente",
          "Offers": "ofertas",
          "Complaints": "Quejas",
          "Issue With": "Problema con",
          "Select Store": "Seleccionar tienda",
          "Select product": "Seleccionar producto",
          "Select Driver": "Seleccionar conductor",
          "Select reason": "Selecciona el motivo",
          "Title": "Título",
          "Brief of your issue": "Resumen de su problema",
          "Comments": "Comentarios",
          "Write something on issue": "Escribe algo sobre el tema",
          "Upload Image": "Cargar imagen",
          "Verify your phone number": "verifica tu numero de telefono",
          "Send OTP": "Enviar OTP",
          "Rate Order": "Orden de tarifa",
          "Driver Information": "Información del conductor",
          "Restaurant Name": "Nombre del restaurante",
          "Tracking Order": "Orden de seguimiento",
          "Order Total": "Total del pedido",
          "Payment Method :": "Método de pago",
          "COD": "BACALAO",
          "PAID": "PAGADO",
          "Start Location": "Ubicación de inicio",
          "End Location": "Ubicación final",
          "Your account is suspended": "Tu cuenta está suspendida",
          "Something went wrong while signup":
              "Algo salió mal durante el registro",
          "Phone Number is required": "Se requiere número de teléfono",
          "Verify": "Verificar",
          "We have sent verification code on":
              "Hemos enviado el código de verificación el",
          "Hey there! What's up>?": "¡Hola! ¿Qué pasa>?",
          "Nothing. Just chilling and watching youtube What about you?":
              "Nada. Solo relajándome y viendo youtube ¿Y tú?",
          "Same here! Been watching youtube for last 5 hours":
              "¡Igual aquí! He estado viendo YouTube durante las últimas 5 horas.",
          "Yeah i know. I am in same position":
              "Si lo se. estoy en la misma posicion",
          "It's hard to be productive man": "Es difícil ser hombre productivo",
          "Sure thankyou": "Seguro, gracias",
          "The product arrived too late": "El producto llego demasiado tarde",
          "The product did not match the description":
              "El producto no coincidía con la descripción.",
          "The purchase was fraudulent": "La compra fue fraudulenta",
          "The product was damaged or defective":
              "El producto estaba dañado o defectuoso",
          "The merchant shipped the wrong item":
              "El comerciante envió el artículo equivocado",
          "Wrong Item Size or Wrong Product Shipped":
              "Tamaño de artículo incorrecto o producto enviado incorrecto",
          "Driver arrived too late": "El conductor llegó demasiado tarde",
          "Driver behavior": "Comportamiento del conductor",
          "Store Vendors behavior":
              "Comportamiento de los vendedores de la tienda",
          "Issue with Payment Amount": "Problema con el monto del pago",
          "Others": "Otros",
          "Order": "Ordenar",
          "Store": "Tienda",
          "Driver": "Conductor",
          "Product": "Producto",
          "Choose Issue With": "Elija Problema con",
          "Choose Store": "Elegir tienda",
          "Choose Driver": "Elegir conductor",
          "Choose Reason": "Elija la razón",
          "Choose Product": "Elija Producto",
          "Complaints registered": "Quejas registradas",
          "NA": "N / A",
          "Stripe": "Raya",
          "PayPal": "Paypal",
          "Paytm": "pago",
          "Razorpay": "maquinilla de afeitar",
          "Instamojo": "Instamojo",
          "Paystack": "pila de pago",
          "Flutterwave": "Onda de aleteo",
          "Requested": "Solicitado",
          "Accepted": "Aceptado",
          "Completed": "Terminado",
          "Rejected": "Rechazado",
        },
        "ar_AE": {
          "Profile": "الملف الشخصي",
          "Edit": "يحرر",
          "Sign In / Sign Up": "تسجيل الدخول / التسجيل",
          "My Orders": "طلباتي",
          "Table Booking": "حجز الجدول",
          "My Favorites": "مفضلتي",
          "Your Address": "عنوانك",
          "Wallet": "Wallet",
          "Refer & Earn": "قم بالإحالة واكسب",
          "Change Password": "غير كلمة السر",
          "Languages": "اللغات",
          "Chats": "الدردشات",
          "Contact Us": "اتصل بنا",
          "Help & Support": "ساعد لدعم",
          "Frequently Asked Questions": "أسئلة مكررة",
          "Terms & Conditions": "البنود و الظروف",
          "About Us": "معلومات عنا",
          "Log Out": "تسجيل خروج",
          "Add New Card": "إضافة بطاقة جديدة",
          "Email Address": "عنوان البريد الالكترونى",
          "Card Holder Name": "إسم صاحب البطاقة",
          "Card Number": "رقم البطاقة",
          "CVV": "CVV",
          "MM/YY": "شهر / سنة",
          "ADD CARD": "إضافة بطاقة",
          "new": "الجديد",
          "Add New Address": "أضف عنوان جديد",
          "Update Address": "تحديث العنوان",
          "Address": "تبوك",
          "House / Flat No": "منزل / شقة لا",
          "Landmark": "معلم معروف",
          "Zipcode": "الرمز البريدي",
          "Optional Phone Number": "رقم هاتف اختياري",
          "SAVE AS": "حفظ باسم",
          "Home": "مسكن",
          "Work": "عمل",
          "Other": "آخر",
          "Submit": "يُقدِّم",
          "Update": "تحديث",
          "Initappz": "إينيتابز",
          "Fresh Food": "طعام طازج",
          "Lapinoz Piza": "بيتزا لا بينوز",
          "McDonalds": "ماكدونالدز",
          "Checkout": "الدفع",
          "At Home": "فى المنزل",
          "Self Pickup": "النفس التقاط",
          "Delivery Address": "عنوان التسليم",
          "Change": "يتغيرون",
          "Store Information": "معلومات المتجر",
          "Apply Coupon Code": "تطبيق رمز القسيمة",
          "Coupon Applied :": " القسيمة المطبقة:",
          "Available Balance": "الرصيد المتوفر",
          "Item Total": "مجموع الاشياء",
          "Taxes & charges": "الضرائب والرسوم",
          "Delivery Cost": "تكلفة التوصيل",
          "Discount": "تخفيض",
          "Wallet Discount": "خصم المحفظة",
          "Grand Total": "المبلغ الإجمالي",
          "Payment Method": "طريقة الدفع او السداد",
          "PLACE ORDER": "مكان الامر",
          "Access Your": "الوصول الخاص بك",
          "Location": "موقع",
          "USE CURRENT LOCATION": "استخدام الموقع الحالي",
          "CHOOSE LOCATION": "اختيار موقع",
          "Full Name": "الاسم الكامل",
          "Message": "رسالة",
          "SUBMIT": "إرسال",
          "Coupens": "كوبونات",
          "Use coupon code": "استخدم رمز القسيمة",
          "- Valid until": "- صالح حتى",
          "Apply": "يتقدم",
          "Cuisines": "المطابخ",
          "Repeat Order": "اعد الامر",
          "Add New": "اضف جديد",
          "Add to cart": "أضف إلى السلة",
          "Best Deals": "افضل العروض",
          "Delivered Here": "سلمت هنا",
          "Edit Profile": "تعديل الملف الشخصي",
          "Choose From": "اختر من",
          "Camera": "آلة تصوير",
          "Gallery": "صالة عرض",
          "Cancel": "يلغي",
          "First Name": "الاسم الاول",
          "Last Name": "الكنية",
          "Email": "البريد الإلكتروني",
          "Mobile": "التليفون المحمول",
          "Save Profile": "احفظ الملف",
          "Connection Failed": "فشل الاتصال",
          "Could not connect to network": "تعذر الاتصال بالشبكة",
          "Please check and try again.": "يرجى مراجعة وحاول مرة أخرى.",
          "retry": "أعد المحاولة",
          "Find Location": "البحث عن الموقع",
          "Search location": "موقع البحث",
          "Use My Current Location": "استخدم موقعي الحالي",
          "Confirm Location": "قم بتأكيد الموقع",
          "Reset Password": "إعادة تعيين كلمة المرور",
          "Enter your email address or phone number and we will send a verification code to generate a new password":
              "أدخل عنوان بريدك الإلكتروني أو رقم هاتفك وسنرسل رمز تحقق لإنشاء كلمة مرور جديدة",
          "SEND": "إرسال",
          "No restaurants near your location": "لا توجد مطاعم بالقرب من موقعك",
          "for 2": "ل 2",
          "Free Delivery": "توصيل مجاني",
          "min": "دقيقة",
          "Ongoing orders": "أوامر جارية",
          "Past Orders": "الطلبات السابقة",
          "No New Orders Found": "لم يتم العثور على طلبات جديدة",
          "No Old Orders Found": "لم يتم العثور على أوامر قديمة",
          "Bhairavpara, 364270": "بهارافبارا ، 364270",
          "Search restaurants": "ابحث عن المطاعم",
          "View All": "مشاهدة الكل",
          "Restaurant near you": "مطعم بالقرب منك",
          "English": "إنجليزي",
          "Arabic": "عربي",
          "Hindi": "هندي",
          "Spanish": "الأسبانية",
          "Log In": "تسجيل الدخول",
          "Password": "كلمة المرور",
          "Forgot Password?": "هل نسيت كلمة السر؟",
          "SIGN IN": "تسجيل الدخول",
          "By Clicking Sign In you certify that you agree to our":
              "بالنقر فوق تسجيل الدخول ، فإنك تقر بموافقتك على",
          "Privacy Policy": "سياسة الخصوصية",
          "and": "و",
          "Terms and Condition": "أحكام وشروط",
          "Or Sign In With": "أو قم بتسجيل الدخول باستخدام",
          "Google": "جوجل",
          "Facebook": "فيسبوك",
          "New user?": "مستخدم جديد؟",
          "Sign Up": "اشتراك",
          "Hardik Rajput": "هارديك راجبوت",
          "Message...": "رسالة...",
          "My Cart": "عربة التسوق الخاصة بي",
          "No Items In Cart": "لا توجد عناصر في سلة التسوق",
          "items": "العناصر",
          "in your cart": "في عربة التسوق الخاصة بك",
          "Notes": "ملحوظات",
          "Total Price": "السعر الكلي",
          "CHECKOUT": "الدفع",
          "Update New Passsword": "تحديث كلمة المرور الجديدة",
          "Generate New Password": "إنشاء كلمة مرور جديدة",
          "New Password": "كلمة السر الجديدة",
          "Confirm New Password": "تأكيد كلمة المرور الجديدة",
          "Update Password": "تطوير كلمة السر",
          "Order Details": "تفاصيل الطلب",
          "Order Number": "رقم الطلب",
          "Payment": "دفع",
          "Delivery": "توصيل",
          "Deliver To": "يسلم إلى",
          "Invite Friends": "ادعو أصدقاء",
          "Create account": "إصنع حساب",
          "Please register to your account": "الرجاء التسجيل في حسابك",
          "Search": "يبحث",
          "Start typing to search": "ابدأ الكتابة للبحث",
          "Phone Number": "رقم الهاتف",
          "Confirm Password": "تأكيد كلمة المرور",
          "Referral Code (Optional)": "إحالة قانون (اختياري)",
          "By Clicking Sign up you certify that you agree to our":
              "بالنقر فوق تسجيل ، فإنك تقر بموافقتك على",
          "Already have an account": "هل لديك حساب",
          "Sign In": "تسجيل الدخول",
          "Browse Menu": "قائمة التصفح",
          "Book Table": "طاولة كتب",
          "Delivery Time": "موعد التسليم",
          "Order For 2": "اطلب 2",
          "Veg": "نباتي",
          "Non-veg": "غير نباتي",
          "No items found!": "لم يتم العثور على العناصر!",
          "Price :": "سعر :",
          "Add": "يضيف",
          "Customisable": "قابل للتخصيص",
          "Items": "العناصر",
          "Cart": "عربة التسوق",
          "Are you sure": "هل أنت واثق",
          "to delete Address ?": "لحذف العنوان؟",
          "Delete": "حذف",
          "Restaurant name": "اسم المطعم",
          "Recently Serched": "بحثت مؤخرا",
          "Clear": "صافي",
          "Skip": "يتخطى",
          "Continue": "يكمل",
          "Next": "التالي",
          "No Internet Connection": "لا يوجد اتصال بالإنترنت",
          "Please wait": "أرجو الإنتظار",
          "Pay With Stripe": "الدفع باستخدام Stripe",
          "Expiry": "انقضاء",
          "History": "تاريخ",
          "Account": "الحساب",
          "Selct An Offer Or Deal": "حدد عرضًا أو صفقة",
          "Select Date": "حدد تاريخ",
          "Select Time": "حدد الوقت",
          "Breakfast": "إفطار",
          "Lunch": "غداء",
          "Dinner": "وجبة عشاء",
          "Enter Guest Detail": "أدخل تفاصيل الضيف",
          "Total Guest": "إجمالي الضيف",
          "Guest Name": "اسم الضيف",
          "Mobile Number": "رقم الهاتف المحمول",
          "Email Id": "عنوان الايميل",
          "Special Request (Optional)": "طلب خاص (اختياري)",
          "Save": "يحفظ",
          "Table List": "قائمة الجدول",
          "Toatal Guest -": "إجمالي الضيف -",
          "Booking Date -": "تاريخ الحجز   -",
          "Guest Name -": "اسم الضيف -",
          "Guest Email -": "ضيف البريد الإلكتروني -",
          "Guest Mobile -": "ضيف موبايل -",
          "Track Order": "ترتيب المسار",
          "Verification": "تَحَقّق",
          "All Transactions": "كل الحركات المالية",
          "An 4-digit verification code has been sent to":
              "تم إرسال رمز تحقق مكون من 4 أرقام إلى",
          "All fields are required": "جميع الحقول مطلوبة",
          "Card Information Saved": "تم حفظ معلومات البطاقة",
          "could not determine your location": "لا يمكن تحديد موقعك",
          "Successfully Added": "أضيف بنجاح",
          "Successfully Updated": "تم التحديث بنجاح",
          "Sorry we deliver the order near to": "نأسف لتسليم الطلب بالقرب من",
          "KM": "كم",
          "Please select payment method": "الرجاء تحديد طريقة الدفع",
          "Orders once placed cannot be cancelled and non-refundable":
              "الطلبات بمجرد تقديمها لا يمكن إلغاؤها وغير قابلة للاسترداد",
          "Place Order": "مكان الامر",
          "Thank You!": "شكرا لك!",
          "For Your Order": "لطلبك",
          "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.":
              "هناك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات في الصفحة التي يقرأها.",
          "Track My Order": "تابع طلبي",
          "Back To Home": "العودة إلى المنزل",
          "Featching Location": "إحضار الموقع",
          "Location services are disabled.": "خدمات الموقع معطلة.",
          "Location permissions are denied": "تم رفض أذونات الموقع",
          "Location permissions are permanently denied, we cannot request permissions.":
              "أذونات الموقع مرفوضة بشكل دائم ، ولا يمكننا طلب أذونات.",
          "Please select offer": "الرجاء تحديد العرض",
          "Please select size": "يرجى تحديد حجم",
          "Profile Updated": "تحديث الملف الشخصي",
          "Email is not valid": "البريد الإلكتروني غير صالح",
          "Your friend": "صديقك",
          "has invited you to": "دعاك إلى",
          "Hey Buddy download": "يا صديقي تنزيل",
          "from app store and use my code":
              "من متجر التطبيقات واستخدم الكود الخاص بي",
          "while sign up we both will get": "أثناء التسجيل سيحصل كلانا",
          "wallet amount": "مبلغ المحفظة",
          "Share with buddies": "شارك مع الأصدقاء",
          "Copied to clipboard": "نسخ إلى الحافظة",
          "Password not match": "كلمة السر ليست جيدة",
          "Getting Rewards": "الحصول على المكافآت",
          "Congratulation": "تهنئة",
          "Close": "قريب",
          "Ok": "موافق",
          "Congratulations your friend have received the":
              "مبروك لقد تلقى صديقك",
          "Congratulations you have received the": "تهانينا ، لقد تلقيت",
          "Congratulations you & your friend have received the ":
              "تهانينا ، لقد تلقيت أنت وصديقك ",
          "Find Food You Love": "ابحث عن الطعام الذي تحبه",
          "Discover the best foods from over 1,000 restaurants and fast delivery to your doorstop":
              "اكتشف أفضل الأطعمة من أكثر من 1000 مطعم وتوصيل سريع إلى باب منزلك",
          "Fast Delivery": "توصيل سريع",
          "Fast delivery to your home,office wherever you are":
              "توصيل سريع إلى منزلك أو مكتبك أينما كنت",
          "Live Tracking": "تتبع مباشر",
          "Real time tracking of your food on the app once you placed the order":
              "تتبع طعامك في الوقت الحقيقي على التطبيق بمجرد تقديم الطلب",
          "Are you sure?": "هل أنت واثق؟",
          "Orders once placed cannot be cancelled and are non-refundable":
              "الطلبات بمجرد تقديمها لا يمكن إلغاؤها وغير قابلة للاسترداد",
          "Yes, Place Order": "نعم ، ضع الطلب",
          "Please select card": "الرجاء تحديد البطاقة",
          "Creating Order": "ترتيب إنشاء",
          "Your Table is successfully booked": "تم حجز طاولتك بنجاح",
          "To Cancel this order?": "لإلغاء هذا الطلب؟",
          "Yes": "نعم",
          "Cancel Order": "الغاء الطلب",
          "Order Accepted": "الطلب مقبول",
          "Order Prepared": "تم إعداد الطلب",
          "Order Ongoing": "الطلب جار",
          "Order Delivered": "تم تسليم الطلب",
          "Order Cancelled": "تم إلغاء الطلب",
          "Order Rejected By Restaurant": "الطلب مرفوض من قبل المطعم",
          "Order Refunded By Administrator": "رد المسؤول الطلب",
          "Payment Pending": "الدفعة معلقة",
          "Offers": "عروض",
          "Complaints": "شكاوي",
          "Issue With": "القضية مع",
          "Select Store": "حدد المتجر",
          "Select product": "حدد المنتج",
          "Select Driver": "حدد السائق",
          "Select reason": "حدد السبب",
          "Title": "عنوان",
          "Brief of your issue": "موجز عن مشكلتك",
          "Comments": "تعليقات",
          "Write something on issue": "اكتب شيئًا عن القضية",
          "Upload Image": "تحميل الصور",
          "Verify your phone number": "اكد على رقم هاتفك او جوالك",
          "Send OTP": "أرسل OTP",
          "Rate Order": "ترتيب معدل",
          "Driver Information": "معلومات السائق",
          "Restaurant Name": "اسم المطعم",
          "Tracking Order": "طلب التتبع",
          "Order Total": "الطلب الكلي",
          "Payment Method :": "طريقة الدفع او السداد",
          "COD": "سمك القد",
          "PAID": "دفع",
          "Start Location": "بدء الموقع",
          "End Location": "موقع النهاية",
          "Your account is suspended": "تم تعليق حسابك",
          "Something went wrong while signup": "حدث خطأ ما أثناء التسجيل",
          "Phone Number is required": "رقم الهاتف مطلوب",
          "Verify": "يؤكد",
          "We have sent verification code on": "لقد أرسلنا رمز التحقق على",
          "Hey there! What's up>?": "مرحبًا يا من هناك! ما الجديد؟",
          "Nothing. Just chilling and watching youtube What about you?":
              "لا شئ. فقط تقشعر لها الأبدان ومشاهدة يوتيوب ماذا عنك؟",
          "Same here! Been watching youtube for last 5 hours":
              "نفس الشيء هنا! كنت أشاهد يوتيوب لمدة 5 ساعات الماضية",
          "Yeah i know. I am in same position": "نعم اعرف. انا في نفس الموقف",
          "It's hard to be productive man": "من الصعب أن تكون رجلاً منتجاً",
          "Sure thankyou": "طبعا شكرا لك",
          "The product arrived too late": "وصل المنتج بعد فوات الأوان",
          "The product did not match the description":
              "المنتج لا يتطابق مع الوصف",
          "The purchase was fraudulent": "كان الشراء احتياليًا",
          "The product was damaged or defective": "المنتج تالف أو به عيب",
          "The merchant shipped the wrong item": "التاجر شحن السلعة الخاطئة",
          "Wrong Item Size or Wrong Product Shipped":
              "حجم السلعة غير صحيح أو شحن منتج خاطئ",
          "Driver arrived too late": "وصل السائق بعد فوات الأوان",
          "Driver behavior": "سلوك السائق",
          "Store Vendors behavior": "سلوك بائعي المتجر",
          "Issue with Payment Amount": "مشكلة في مبلغ الدفع",
          "Others": "آحرون",
          "Order": "ترتيب",
          "Store": "متجر",
          "Driver": "سائق",
          "Product": "منتج",
          "Choose Issue With": "اختر المشكلة مع",
          "Choose Store": "اختر المتجر",
          "Choose Driver": "اختر السائق",
          "Choose Reason": "اختر السبب",
          "Choose Product": "اختر المنتج",
          "Complaints registered": "تم تسجيل الشكاوى",
          "NA": "غير متوفر",
          "Stripe": "شريط",
          "PayPal": "باي بال",
          "Paytm": "Paytm",
          "Razorpay": "رازورباي",
          "Instamojo": "إنستاموجو",
          "Paystack": "Paystack",
          "Flutterwave": "Flutterwave",
          "Requested": "مطلوب",
          "Accepted": "وافقت",
          "Completed": "مكتمل",
          "Rejected": "مرفوض",
        },
      };
}
