/*
  Authors : initappz (Rahul Jograna)
  Website : https://initappz.com/
  App Name : Foodies Full App Flutter
  This App Template Source code is licensed as per the
  terms found in the Website https://initappz.com/license
  Copyright and Good Faith Purchasers © 2022-present initappz.
*/
import 'package:get/get.dart';

class LocaleString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          "Contact Us": "Contact Us",
          "App Pages": "App Pages",
          "Full Name": "Full Name",
          "Email Address": "Email Address",
          "Message": "Message",
          "Submit": "Submit",
          "Edit Profile": "Edit Profile",
          "First Name -": "First Name -",
          "Jaydeep": "Jaydeep",
          "Last Name -": "Last Name -",
          "Hirani": "Hirani",
          "Email -": "Email -",
          "Mobile -": "Mobile -",
          "Available": "Available",
          "jaydeephirani5@gmail.com": "jaydeephirani5@gmail.com",
          "Connection Failed": "Connection Failed",
          "Could not connect to network": "Could not connect to network",
          "Please check and try again.": "Please check and try again.",
          "retry": "retry",
          "Reset Password": "Reset Password",
          "Enter your email address or phone number and we will send a verification code to generate a new password":
              "Enter your email address or phone number and we will send a verification code to generate a new password",
          "Languages": "Languages",
          "Send": "Send",
          "English": "English",
          "Arabic": "Arabic",
          "Hindi": "Hindi",
          "Spanish": "Spanish",
          "Log In": "Log In",
          "Password": "Password",
          "Forgot Password?": "Forgot Password?",
          "Sign in": "Sign in",
          "Update New Passsword": "Update New Passsword",
          "Generate New Password": "Generate New Password",
          "New Password": "New Password",
          "Confirm New Password": "Confirm New Password",
          "Update Password": "Update Password",
          "Orders": "Orders",
          "Order Detail": "Order Detail",
          "Item Total": "Item Total",
          "Taxes & charges": "Taxes & charges",
          "Delivery Cost": "Delivery Cost",
          "Discount": "Discount",
          "Wallet Discount": "Wallet Discount",
          "Grand Total": "Grand Total",
          "Order ID :": "Order ID",
          "Payment Method": "Payment Method",
          "Delivery On": "Delivery On",
          "Delivery To": "Delivery To",
          "Update Status": "Update Status",
          "Current Order": "Current Order",
          "Past Order": "Past Order",
          "ORDER ID": "ORDER ID",
          "ORDERED ON": "ORDERED ON",
          "TOTAL AMOUNT": "TOTAL AMOUNT",
          "ORDER ID :": "ORDER ID :",
          "Jaydeep Hirani": "Jaydeep Hirani",
          "jaydeep@initappz.com": "jaydeep@initappz.com",
          "Reviews": "Reviews",
          "Change password": "Change password",
          "About Us": "About Us",
          "FAQs": "FAQs",
          "Help": "Help",
          "Log Out": "Log Out",
          "Received from manually": "Received from manually",
          "Rahul Jograna": "Rahul Jograna",
          "Good....Very good...": "Good....Very good...",
          "Jun 11, 2022 12:00 AM": "Jun 11, 2022 12:00 AM",
          "No Internet Connection": "No Internet Connection",
          "Please wait": "Please wait",
          "Profile": "Profile",
          "Verification": "Verification",
          "An 4-digit verification code has been sent to":
              "An 4-digit verification code has been sent to",
          "Continue": "Continue",
          "All fields are required": "All fields are required",
          "Email is not valid": "Email is not valid",
          "Updating Status": "Updating Status",
          "Status Updated": "Status Updated",
          "Accepted": "Accepted",
          "Prepared": "Prepared",
          "Ongoing": "Ongoing",
          "Delivered": "Delivered",
          "Home": "Home",
          "Work": "Work",
          "Others": "Others",
          "COD": "COD",
          "Stripe": "Stripe",
          "PayPal": "PayPal",
          "Paytm": "Paytm",
          "Razorpay": "Razorpay",
          "Instamojo": "Instamojo",
          "Paystack": "Paystack",
          "Flutterwave": "Flutterwave",
          "Chats": "Chats ",
          "Choose From": "Choose From ",
          "Camera": "Camera ",
          "Gallery": "Gallery ",
          "Cancel": "Cancel ",
          "Send OTP": "Send OTP ",
          "Confirm Password": "Confirm Password ",
          "Message...": "Message... ",
          "Store Information": "Store Information ",
          "User Information": "User Information ",
          "No New Orders Found": "No New Orders Found ",
          "Terms & Conditions": "Terms & Conditions ",
          "Privacy Policy": "Privacy Policy ",
          "No Reviews Found": "No Reviews Found ",
          "Tracking Order": "Tracking Order ",
          "Order Total": "Order Total ",
          "Payment Method :": "Payment Method  ",
          "PAID": "PAID ",
          "New Mail Request Received": "New Mail Request Received ",
          "You have received new mail": "You have received new mail ",
          "New Contact Details": "New Contact Details ",
          "We have received your request, we will respond on your issue soon":
              "We have received your request we will respond on your issue soon",
          "Alert!": "Alert! ",
          "Okay": "Okay ",
          "Something went wrong while signup":
              "Something went wrong while signup ",
          "Something went wrong": "Something went wrong ",
          "We have sent verification code on":
              "We have sent verification code on ",
          "Verify": "Verify ",
          "Password mismatch": "Password mismatch ",
          "Password Updated": "Password Updated ",
          "Your account is suspended": "Your account is suspended ",
          "NA": "NA ",
          "Start Location": "Start Location ",
          "End Location": "End Location ",
          "Contact": "Contact ",
          "Call": "Call",
        },
        'hi_IN': {
          "Contact Us": "संपर्क करें",
          "App Pages": "ऐप पेज",
          "Full Name": "पूरा नाम",
          "Email Address": "ईमेल पता",
          "Message": "संदेश",
          "Submit": "प्रस्तुत करना",
          "Edit Profile": "प्रोफ़ाइल संपादित करें",
          "First Name -": "पहला नाम",
          "Jaydeep": "जयदीप",
          "Last Name -": "उपनाम -",
          "Hirani": "हिरानी",
          "Email -": "ईमेल -",
          "Mobile -": "गतिमान -",
          "Available": "उपलब्ध",
          "jaydeephirani5@gmail.com": "jaydeephirani5@gmail.com",
          "Connection Failed": "कनेक्शन विफल",
          "Could not connect to network": "नेटवर्क से कनेक्ट नहीं हो सका",
          "Please check and try again.": "कृपया जाँच करें और पुनः प्रयास करें",
          "retry": "पुन: प्रयास करें",
          "Reset Password": "पासवर्ड रीसेट",
          "Enter your email address or phone number and we will send a verification code to generate a new password":
              "अपना ईमेल पता या फोन नंबर दर्ज करें और हम एक नया पासवर्ड बनाने के लिए एक सत्यापन कोड भेजेंगे",
          "Languages": "बोली",
          "Send": "भेजना",
          "English": "अंग्रेज़ी",
          "Arabic": "अरबी",
          "Hindi": "हिन्दी",
          "Spanish": "स्पैनिश",
          "Log In": "लॉग इन करें",
          "Password": "पासवर्ड",
          "Forgot Password?": "पासवर्ड भूल गए",
          "Sign in": "साइन इन करें",
          "Update New Passsword": "नया पासवर्ड अपडेट करें",
          "Generate New Password": "नया पासवर्ड जनरेट करें",
          "New Password": "नया पासवर्ड",
          "Confirm New Password": "नए पासवर्ड की पुष्टि करें",
          "Update Password": "पासवर्ड अपडेट करें",
          "Orders": "आदेश",
          "Order Detail": "ऑर्डर विवरण",
          "Item Total": "आइटम का कुल",
          "Taxes & charges": "कर और शुल्क",
          "Delivery Cost": "वितरण लागत",
          "Discount": "छूट",
          "Wallet Discount": "वॉलेट छूट",
          "Grand Total": "कुल योग",
          "Order ID :": "आदेश ID",
          "Payment Method": "भुगतान का तरीका",
          "Delivery On": "डिलीवरी चालू",
          "Delivery To": "को सुपुर्दगी",
          "Update Status": "नवीनतम स्थिति",
          "Current Order": "अभी का ऑर्डर",
          "Past Order": "पिछला आदेश",
          "ORDER ID": "आदेश ID",
          "ORDERED ON": "आदेश दिया गया",
          "TOTAL AMOUNT": "कुल राशि",
          "ORDER ID :": "आदेश ID",
          "Jaydeep Hirani": "जयदीप हिरानी",
          "jaydeep@initappz.com": "jaydeep@initappz.com",
          "Reviews": "समीक्षा",
          "Change password": "पासवर्ड बदलें",
          "About Us": "हमारे बारे में",
          "FAQs": "पूछे जाने वाले प्रश्न",
          "Help": "मदद करना",
          "Log Out": "लॉग आउट",
          "Received from manually": "मैन्युअल रूप से प्राप्त",
          "Rahul Jograna": "राहुल जोगराना",
          "Good....Very good...": "अच्छा बहुत अच्छा",
          "Jun 11, 2022 12:00 AM": "जून 11, 2022 12:00 पूर्वाह्न",
          "No Internet Connection": "कोई इंटरनेट कनेक्शन नहीं",
          "Please wait": "कृपया प्रतीक्षा करें",
          "Profile": "प्रोफ़ाइल",
          "Verification": "सत्यापन",
          "An 4-digit verification code has been sent to":
              "4 अंकों का सत्यापन कोड . को भेज दिया गया है",
          "Continue": "जारी रखना",
          "All fields are required": "सभी फ़ील्ड आवश्यक हैं",
          "Email is not valid": "विद्युतडाक मान्य नहीं है",
          "Updating Status": "अद्यतन स्थिति",
          "Status Updated": "स्थिति अपडेट",
          "Accepted": "को स्वीकृत",
          "Prepared": "तैयार",
          "Ongoing": "चल रहे",
          "Delivered": "पहुंचा दिया",
          "Home": "घर",
          "Work": "काम",
          "Others": "अन्य",
          "COD": "सीओडी",
          "Stripe": "पट्टी",
          "PayPal": "पेपैल",
          "Paytm": "Paytm",
          "Razorpay": "रेज़रपे",
          "Instamojo": "इंस्टामोजो",
          "Paystack": "पेस्टैक",
          "Flutterwave": "स्पंदन तरंग",
          "Chats": "चैट",
          "Choose From": "से चुनें",
          "Camera": "कैमरा",
          "Gallery": "गेलरी",
          "Cancel": "रद्द करना",
          "Send OTP": "OTP भेजें",
          "Confirm Password": "पासवर्ड की पुष्टि कीजिये",
          "Message...": "संदेश...",
          "Store Information": "जानकारी जमा करो",
          "User Information": "उपयोगकर्ता के लिए जानकारी",
          "No New Orders Found": "कोई नया आदेश नहीं मिला",
          "Terms & Conditions": "नियम एवं शर्तें",
          "Privacy Policy": "गोपनीयता नीति",
          "No Reviews Found": "कोई समीक्षा नहीं मिली",
          "Tracking Order": "ट्रैकिंग आदेश",
          "Order Total": "कुल आर्डर",
          "Payment Method :": "भुगतान का तरीका",
          "PAID": "भुगतान किया है",
          "New Mail Request Received": "नया मेल अनुरोध प्राप्त हुआ",
          "You have received new mail": "आपको नया मेल प्राप्त हुआ है",
          "New Contact Details": "नया संपर्क विवरण",
          "We have received your request, we will respond on your issue soon":
              "हमें आपका अनुरोध प्राप्त हो गया है हम जल्द ही आपके मुद्दे पर प्रतिक्रिया देंगे",
          "Alert!": "चेतावनी!",
          "Okay": "ठीक",
          "Something went wrong while signup": "साइन अप करते समय कुछ गलत हुआ",
          "Something went wrong": "कुछ गलत हो गया",
          "We have sent verification code on": "हमने सत्यापन कोड को भेजा है",
          "Verify": "सत्यापित करना",
          "Password mismatch": "पासवर्ड का मेल नहीं हुआ",
          "Password Updated": "पासवर्ड अपडेट किया गया",
          "Your account is suspended": "तुम्हारा खाता निलंबित है",
          "NA": "ना",
          "Start Location": "प्रारंभ स्थान",
          "End Location": "अंतिम स्थान",
          "Contact": "संपर्क करना",
          "Call": "बुलाना",
        },
        'es_DE': {
          "Contact Us": "Contáctenos",
          "App Pages": "Páginas de aplicaciones",
          "Full Name": "Nombre completo",
          "Email Address": "Dirección de correo electrónico",
          "Message": "Mensaje",
          "Submit": "Enviar",
          "Edit Profile": "Editar perfil",
          "First Name -": "Primer nombre",
          "Jaydeep": "jaydeep",
          "Last Name -": "Apellido -",
          "Hirani": "hirani",
          "Email -": "Correo electrónico -",
          "Mobile -": "Móvil -",
          "Available": "Disponible",
          "jaydeephirani5@gmail.com": "jaydeephirani5@gmail.com",
          "Connection Failed": "La conexión falló",
          "Could not connect to network": "No se pudo conectar a la red",
          "Please check and try again.": "Por favor revisa e intenta de nuevo",
          "retry": "rever",
          "Reset Password": "Restablecer la contraseña",
          "Enter your email address or phone number and we will send a verification code to generate a new password":
              "Ingrese su dirección de correo electrónico o número de teléfono y le enviaremos un código de verificación para generar una nueva",
          "Languages": "contraseña",
          "Send": "Idiomas",
          "English": "Enviar",
          "Arabic": "Arábica",
          "Hindi": "hindi",
          "Spanish": "español",
          "Log In": "Iniciar sesión",
          "Password": "Clave",
          "Forgot Password?": "Has olvidado tu contraseña",
          "Sign in": "Iniciar sesión",
          "Update New Passsword": "Actualizar nueva contraseña",
          "Generate New Password": "Generar nueva contraseña",
          "New Password": "Nueva contraseña",
          "Confirm New Password": "Confirmar nueva contraseña",
          "Update Password": "Actualiza contraseña",
          "Orders": "Pedidos",
          "Order Detail": "Detalle de la orden",
          "Item Total": "Total",
          "Taxes & charges": "Impuestos y cargos",
          "Delivery Cost": "Coste de envío",
          "Discount": "Descuento",
          "Wallet Discount": "Descuento de billetera",
          "Grand Total": "Gran total",
          "Order ID :": "Solicitar ID",
          "Payment Method": "Método de pago",
          "Delivery On": "Entrega en",
          "Delivery To": "Entregar a",
          "Update Status": "Estado de actualización",
          "Current Order": "Orden actual",
          "Past Order": "Orden pasada",
          "ORDER ID": "SOLICITAR ID",
          "ORDERED ON": "PEDIDO EL",
          "TOTAL AMOUNT": "CANTIDAD TOTAL",
          "ORDER ID :": "SOLICITAR ID",
          "Jaydeep Hirani": "jaydeep hirani",
          "jaydeep@initappz.com": "jaydeep@initappz.com",
          "Reviews": "Reseñas",
          "Change password": "Cambia la contraseña",
          "About Us": "Sobre nosotros",
          "FAQs": "preguntas frecuentes",
          "Help": "Ayuda",
          "Log Out": "Cerrar sesión",
          "Received from manually": "Recibido de forma manual",
          "Rahul Jograna": "Raul Jograna",
          "Good....Very good...": "Bueno muy bueno",
          "Jun 11, 2022 12:00 AM": "11 de junio de 2022 00:00",
          "No Internet Connection": "Sin conexión a Internet",
          "Please wait": "Espere por favor",
          "Profile": "Perfil",
          "Verification": "Verificación",
          "An 4-digit verification code has been sent to":
              "Se ha enviado un código de verificación de 4 dígitos a",
          "Continue": "Continuar",
          "All fields are required": "Todos los campos son obligatorios",
          "Email is not valid": "El correo no es válido",
          "Updating Status": "Actualización de estado",
          "Status Updated": "Estado actualizado",
          "Accepted": "Aceptado",
          "Prepared": "Preparado",
          "Ongoing": "En curso",
          "Delivered": "Entregado",
          "Home": "Hogar",
          "Work": "Trabajar",
          "Others": "Otros",
          "COD": "BACALAO",
          "Stripe": "Raya",
          "PayPal": "Paypal",
          "Paytm": "pago",
          "Razorpay": "maquinilla de afeitar",
          "Instamojo": "Instamojo",
          "Paystack": "pila de pago",
          "Flutterwave": "Onda de aleteo",
          "Chats": "charlas",
          "Choose From": "Escoge de",
          "Camera": "Cámara",
          "Gallery": "Galería",
          "Cancel": "Cancelar",
          "Send OTP": "Enviar OTP",
          "Confirm Password": "Confirmar contraseña",
          "Message...": "Mensaje...",
          "Store Information": "Almacenar información",
          "User Information": "informacion del usuario",
          "No New Orders Found": "No se encontraron nuevos pedidos",
          "Terms & Conditions": "Términos y condiciones",
          "Privacy Policy": "Política de privacidad",
          "No Reviews Found": "No se encontraron comentarios",
          "Tracking Order": "Orden de seguimiento",
          "Order Total": "Total del pedido",
          "Payment Method :": "Método de pago",
          "PAID": "PAGADO",
          "New Mail Request Received": "Nueva solicitud de correo recibida",
          "You have received new mail": "Has recibido correo nuevo",
          "New Contact Details": "Nuevos detalles de contacto",
          "We have received your request, we will respond on your issue soon":
              "Hemos recibido su solicitud, pronto responderemos a su problema.",
          "Alert!": "¡Alerta!",
          "Okay": "De acuerdo",
          "Something went wrong while signup":
              "Algo salió mal durante el registro",
          "Something went wrong": "Algo salió mal",
          "We have sent verification code on":
              "Hemos enviado el código de verificación el",
          "Verify": "Verificar",
          "Password mismatch": "Contraseña no coincide",
          "Password Updated": "Contraseña actualiza",
          "Your account is suspended": "Tu cuenta está suspendida",
          "NA": "N / A",
          "Start Location": "Ubicación de inicio",
          "End Location": "Ubicación final",
          "Contact": "Contacto",
          "Call": "Llamar",
        },
        'ar_AE': {
          "Contact Us": "اتصل بنا",
          "App Pages": "صفحات التطبيق",
          "Full Name": "الاسم الكامل",
          "Email Address": "عنوان البريد الالكترونى",
          "Message": "رسالة",
          "Submit": "يُقدِّم",
          "Edit Profile": "تعديل الملف الشخصي",
          "First Name -": "الاسم الاول",
          "Jaydeep": "جايدب",
          "Last Name -": "الكنية -",
          "Hirani": "هيراني",
          "Email -": "البريد الإلكتروني -",
          "Mobile -": "متحرك -",
          "Available": "متوفرة",
          "jaydeephirani5@gmail.com": "jaydeephirani5@gmail.com",
          "Connection Failed": "فشل الاتصال",
          "Could not connect to network": "تعذر الاتصال بالشبكة",
          "Please check and try again.": "يرجى مراجعة وحاول مرة أخرى",
          "retry": "أعد المحاولة",
          "Reset Password": "إعادة تعيين كلمة المرور",
          "Enter your email address or phone number and we will send a verification code to generate a new password":
              "أدخل عنوان بريدك الإلكتروني أو رقم هاتفك وسنرسل رمز تحقق لإنشاء كلمة مرور جديدة",
          "Languages": "اللغات",
          "Send": "إرسال",
          "English": "إنجليزي",
          "Arabic": "عربي",
          "Hindi": "هندي",
          "Spanish": "الأسبانية",
          "Log In": "تسجيل الدخول",
          "Password": "كلمة المرور",
          "Forgot Password?": "هل نسيت كلمة السر",
          "Sign in": "تسجيل الدخول",
          "Update New Passsword": "تحديث New Passsword",
          "Generate New Password": "إنشاء كلمة مرور جديدة",
          "New Password": "كلمة السر الجديدة",
          "Confirm New Password": "تأكيد كلمة المرور الجديدة",
          "Update Password": "تطوير كلمة السر",
          "Orders": "الطلب #٪ s",
          "Order Detail": "تفاصيل الطلب",
          "Item Total": "مجموع الاشياء",
          "Taxes & charges": "الضرائب والرسوم",
          "Delivery Cost": "تكلفة التوصيل",
          "Discount": "تخفيض",
          "Wallet Discount": "خصم المحفظة",
          "Grand Total": "المبلغ الإجمالي",
          "Order ID :": "رقم التعريف الخاص بالطلب",
          "Payment Method": "طريقة الدفع او السداد",
          "Delivery On": "التسليم في",
          "Delivery To": "تسليم الى",
          "Update Status": "تحديث الحالة",
          "Current Order": "الترتيب الحالي",
          "Past Order": "طلب سابق",
          "ORDER ID": "رقم التعريف الخاص بالطلب",
          "ORDERED ON": "تم طلبه في",
          "TOTAL AMOUNT": "المبلغ الإجمالي",
          "ORDER ID :": "رقم التعريف الخاص بالطلب",
          "Jaydeep Hirani": "جايدب هيراني",
          "jaydeep@initappz.com": "jaydeep@initappz.com",
          "Reviews": "المراجعات",
          "Change password": "غير كلمة السر",
          "About Us": "معلومات عنا",
          "FAQs": "أسئلة وأجوبة",
          "Help": "مساعدة",
          "Log Out": "تسجيل خروج",
          "Received from manually": "وردت من يدويا",
          "Rahul Jograna": "راهول جوجرانا",
          "Good....Very good...": "جيد جيد جدا",
          "Jun 11, 2022 12:00 AM": "11 يونيو 2022 12:00 ص",
          "No Internet Connection": "لا يوجد اتصال بالإنترنت",
          "Please wait": "أرجو الإنتظار",
          "Profile": "الملف الشخصي",
          "Verification": "تَحَقّق",
          "An 4-digit verification code has been sent to":
              "تم إرسال رمز تحقق مكون من 4 أرقام إلى",
          "Continue": "يكمل",
          "All fields are required": "جميع الحقول مطلوبة",
          "Email is not valid": "البريد الإلكتروني غير صالح",
          "Updating Status": "تحديث الحالة",
          "Status Updated": "تم تحديث الحالة",
          "Accepted": "وافقت",
          "Prepared": "أعدت",
          "Ongoing": "جاري التنفيذ",
          "Delivered": "تم التوصيل",
          "Home": "مسكن",
          "Work": "عمل",
          "Others": "آحرون",
          "COD": "سمك القد",
          "Stripe": "شريط",
          "PayPal": "باي بال",
          "Paytm": "Paytm",
          "Razorpay": "رازورباي",
          "Instamojo": "إنستاموجو",
          "Paystack": "Paystack",
          "Flutterwave": "Flutterwave",
          "Chats": "الدردشات",
          "Choose From": "اختر من",
          "Camera": "آلة تصوير",
          "Gallery": "صالة عرض",
          "Cancel": "يلغي",
          "Send OTP": "أرسل OTP",
          "Confirm Password": "تأكيد كلمة المرور",
          "Message...": "رسالة...",
          "Store Information": "معلومات المتجر",
          "User Information": "معلومات المستخدم",
          "No New Orders Found": "لم يتم العثور على طلبات جديدة",
          "Terms & Conditions": "البنود و الظروف",
          "Privacy Policy": "سياسة الخصوصية",
          "No Reviews Found": "لا توجد مراجعات",
          "Tracking Order": "طلب التتبع",
          "Order Total": "الطلب الكلي",
          "Payment Method :": "طريقة الدفع او السداد",
          "PAID": "دفع",
          "New Mail Request Received": "تم استلام طلب بريد جديد",
          "You have received new mail": "لقد تلقيت بريدًا جديدًا",
          "New Contact Details": "تفاصيل جهة اتصال جديدة",
          "We have received your request, we will respond on your issue soon":
              "لقد تلقينا طلبك وسنرد على مشكلتك قريبًا",
          "Alert!": "انذار!",
          "Okay": "تمام",
          "Something went wrong while signup": "حدث خطأ ما أثناء التسجيل",
          "Something went wrong": "هناك خطأ ما",
          "We have sent verification code on": "لقد أرسلنا رمز التحقق على",
          "Verify": "يؤكد",
          "Password mismatch": "كلمة المرور غير متطابقة",
          "Password Updated": "تم تحديث كلمة السر",
          "Your account is suspended": "تم تعليق حسابك",
          "NA": "غير متوفر",
          "Start Location": "بدء الموقع",
          "End Location": "موقع النهاية",
          "Contact": "اتصال",
          "Call": "مكالمة",
        },
      };
}
