// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTH5ID90dBv0-vWo50e3grkUZmMLo2YoY',
    appId: '1:716618678773:web:1583f48a8ed45e5fdc20bc',
    messagingSenderId: '716618678773',
    projectId: 'enovy-260bf',
    authDomain: 'enovy-260bf.firebaseapp.com',
    storageBucket: 'enovy-260bf.appspot.com',
    measurementId: 'G-83NR55CYV5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzdmqg_UeaPWAyP-5-bctInkpSotYXGB4',
    appId: '1:716618678773:android:4f46f9ebb0f64e2edc20bc',
    messagingSenderId: '716618678773',
    projectId: 'enovy-260bf',
    storageBucket: 'enovy-260bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBABhwkUqiVv_iftGXGGmGclGxltXmmpqI',
    appId: '1:716618678773:ios:2f838b154414a14cdc20bc',
    messagingSenderId: '716618678773',
    projectId: 'enovy-260bf',
    storageBucket: 'enovy-260bf.appspot.com',
    iosBundleId: 'io.initappz.foodies.user',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBABhwkUqiVv_iftGXGGmGclGxltXmmpqI',
    appId: '1:716618678773:ios:b77b9b7b7ef6c71adc20bc',
    messagingSenderId: '716618678773',
    projectId: 'enovy-260bf',
    storageBucket: 'enovy-260bf.appspot.com',
    iosBundleId: 'com.example.foodiesUser',
  );
}
